insert into `legislator`
	values(1, 'Aquilino Martin', 'de la Llana', 'Pimentel III', str_to_date('01-20-1964', '%c-%d-%Y'), 'M', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2022', '%c-%d-%Y'));
insert into `legislator`
	values(2, 'Paolo Benigno', 'Aguirre', 'Aquino IV', str_to_date('05-07-1977', '%c-%d-%Y'), 'M', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(3, 'Miriam Palma', 'Defensor', 'Santiago', str_to_date('06-15-1945', '%c-%d-%Y'), 'F', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(4, 'Loren Regina', 'Bautista', 'Legarda', str_to_date('01-28-1960', '%c-%d-%Y'), 'F', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(5, 'Jose', 'Pimentel' 'Ejercito-Estrada', str_to_date('01-23-1963', '%c-%d-%Y'), 'M', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(6, 'Teofisto', 'de Lara', 'Guingona III', str_to_date('04-19-1959', '%c-%d-%Y'), 'M', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(7, 'Ramon', '', 'Revilla JR.', str_to_date('09-25-1966', '%c-%d-%Y'), 'M', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(8, 'Francis Josepp', 'Guevara', 'Escudero', str_to_date('10-10-1969', '%c-%d-%Y'), 'M', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(9, 'Pilar Juliana', 'Schramm', 'Cayetano', str_to_date('03-22-1966', '%c-%d-%Y'), 'F', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(10, 'Juan Edgardo', 'Manalang', 'Angara', str_to_date('07-15-1943', '%c-%d-%Y'), 'M', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(11, 'Joseph Victor', 'Gomez', 'Ejercito', str_to_date('12-26-1969', '%c-%d-%Y'), 'M', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(12, 'Antonio', 'Fuentes', 'Trillanes', str_to_date('08-06-1971', '%c-%d-%Y'), 'M', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(13, 'Mary Grace', 'Llamanzares', 'Poe', str_to_date('01-01-1968', '%c-%d-%Y'), 'F', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(14, 'Maria Lourdes Nancy', 'Sombillo', 'Binay', str_to_date('05-12-1973', '%c-%d-%Y'), 'F', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(15, 'Manuel', 'Mercado', 'Lapid', str_to_date('08-21-1955', '%c-%d-%Y'), 'M', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(16, 'Ferdinand', 'Romualdez', 'Marcos', str_to_date('09-13-1957', '%c-%d-%Y'), 'M', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

insert into `bill`
	values(3220, 'TAX AND DUTIES EXEMPTIONS THE PRIZES OF MISS UNIVERSE PIA WURTZBACH',
		'AN ACT EXEMPTING FROM INCOME TAX, VALUE-ADDED TAX, AND IMPORT DUTIES THE WINNINGS AND/OR PRIZES OF MISS PIA ALONZO WURTZBACH AS MISS UNIVERSE 2015, AND FROM DONOR\'S TAX ANY DONATION MADE BY HER FROM SUCH WINNINGS AND/OR PRIZES',
		'SENATE BILL', 'NATIONAL', 'ARCHIVED', null, str_to_date('2016-02-03', '%Y-%c-%d'));
	insert into `bill_author` values(3220, 1);
	insert into `bill_subject` values(3220, 'VALUE-ADDED TAX');
	insert into `bill_subject` values(3220, 'TAX EXEMPTON');

insert into `bill`
	values(3221, 'ORGAN AND TISSUE DONATION ACT OF 2016',
		'AN ACT STRENGTHENING THE HUMAN ORGAN AND TISSUE DONATION AND TRANSPLANTATION PROGRAM AND PROVIDING PENALTIES FOR VIOLATION THEREOF, AMENDING FOR THIS PURPOSE REPUBLIC ACT NO. 7170, AS AMENDED, ALSO KNOWN AS THE ORGAN DONATION ACT OF 1991',
		'SENATE BILL', 'NATIONAL', 'PENDING', '2ND', str_to_date('2016-02-03', '%Y-%c-%d')) ;
	insert into `bill_author` values (3221, 3);
	insert into `bill_author` values(3221, 4);
	insert into `bill_author` values(3221, 5);
	insert into `bill_author` values(3221, 6);
	insert into `bill_subject` values(3221, 'ORGAN DONATION');

insert into `bill`
	values(3222, 'SUMMARY TITLING OF REAL PROPERTIES USED AS PUBLIC SCHOOL SITES',
		'AN ACT PROVIDING FOR THE SUMMARY TITLING OF REAL PROPERTIES USED AS PUBLIC SCHOOL SITES',
		'SENATE BILL', 'NATIONAL', 'COMM REPORT ARCHIVED', NULL, str_to_date('2016-02-03', '%Y-%c-%d'));
	insert into `bill_author` values(3222, 7);
	insert into `bill_author` values(3222, 8);
	insert into `bill_author` values(3222, 9);
	insert into `bill_author` values(3222, 4);
	insert into `bill_author` values(3222, 10);
	insert into `bill_subject` values(3222, 'REAL PROPERTIES');

insert into `bill`
	values(3223, 'PHILIPPINE HIV AND AIDS ACT',
		'AN ACT STRENGTHENING THE PHILIPPINE COMPREHENSIVE POLICY ON HIV AND AIDS PREVENTION, TREATMENT, CARE, AND SUPPORT, REPEALING FOR THE PURPOSE REPUBLIC ACT NO. 8504, OTHERWISE KNOWN AS THE PHILIPPINE AIDS PREVENTION AND CONTROL ACT OF 1998, AND APPROPRIATING FUNDS THEREFORE',
		'SENATE BILL', 'NATIONAL', 'PENDING', '2ND', str_to_date('2016-02-03', '%Y-%c-%d'));
	insert into `bill_author` values(3223, 1);
	insert into `bill_author` values(3223, 3);
	insert into `bill_author` values(3223, 4);
	insert into `bill_author` values(3223, 5);
	insert into `bill_author` values(3223, 6);
	insert into `bill_author` values(3223, 9);
	insert into `bill_author` values(3223, 11);
	insert into `bill_author` values(3223, 12);
	insert into `bill_author` values(3223, 13);
	insert into `bill_author` values(3223, 14);
	insert into `bill_author` values(3223, 15);
	insert into `bill_author` values(3223, 2);

insert into `bill`
	values(3224, "SOLO PARENTS AND THEIR CHILDREN'S WELFARE ACT", 'AN ACT AMENDING REPUBLIC ACT NO. 8972, OTHERWISE KNOWN AS THE SOLO PARENTS WELFARE ACT OF 2000, AND FOR OTHER PURPOSES',
		'SENATE BILL', 'NATIONAL', 'ARCHIVED', null, str_to_date('02-09-2016', '%c-%d-%Y'));
	insert into `bill_author` values(3224, 16);
	insert into `bill_subject` values(3224, "R.A. No. 8972");

insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (17, 'Cory', 'Stockney', 'Charrisson', str_to_date('10/13/1955', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 27416, 2, str_to_date('4/1/2011', '%c/%d/%Y'), str_to_date('8/22/2017', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (18, 'Mariska', 'Carbry', 'Tills', str_to_date('06/21/1957', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 33364, 2, str_to_date('6/7/2014', '%c/%d/%Y'), str_to_date('12/29/2006', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (19, 'Lari', 'Gladden', 'Haworth', str_to_date('09/23/1956', '%c/%d/%Y'), 'F', 'SENATOR', 25672, 2, str_to_date('8/9/2007', '%c/%d/%Y'), str_to_date('11/3/2011', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (20, 'Aldous', 'Greig', 'Forbes', str_to_date('10/22/1954', '%c/%d/%Y'), 'M', 'SENATOR', 10739, 0, str_to_date('1/22/2014', '%c/%d/%Y'), str_to_date('1/28/2007', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (21, 'Natassia', 'Fetherston', 'Klaiser', str_to_date('07/21/1969', '%c/%d/%Y'), 'F', 'SENATOR', 22617, 1, str_to_date('12/2/2011', '%c/%d/%Y'), str_to_date('3/8/2014', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (22, 'Mel', 'Moyles', 'Trussler', str_to_date('08/26/1952', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 13043, 0, str_to_date('10/3/2009', '%c/%d/%Y'), str_to_date('12/23/2009', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (23, 'Liesa', 'Genney', 'Senechell', str_to_date('08/29/1939', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 31114, 0, str_to_date('12/12/2007', '%c/%d/%Y'), str_to_date('3/26/2012', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (24, 'Auria', 'Tiery', 'McEnery', str_to_date('09/05/1934', '%c/%d/%Y'), 'F', 'SENATOR', 37468, 2, str_to_date('1/9/2011', '%c/%d/%Y'), str_to_date('6/10/2005', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (25, 'Hilarius', 'McFeat', 'Kolodziejski', str_to_date('04/14/1940', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 19175, 1, str_to_date('5/17/2015', '%c/%d/%Y'), str_to_date('4/2/2017', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (26, 'Ringo', 'Runnacles', 'Corzon', str_to_date('12/18/1960', '%c/%d/%Y'), 'M', 'SENATOR', 18873, 0, str_to_date('9/8/2009', '%c/%d/%Y'), str_to_date('7/21/2015', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (27, 'Birch', 'Hevey', 'Finnes', str_to_date('06/29/1943', '%c/%d/%Y'), 'M', 'SENATOR', 14759, 1, str_to_date('5/28/2010', '%c/%d/%Y'), str_to_date('3/6/2019', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (28, 'Fidelia', 'Waye', 'Scholey', str_to_date('04/07/1937', '%c/%d/%Y'), 'F', 'SENATOR', 34703, 0, str_to_date('6/8/2014', '%c/%d/%Y'), str_to_date('2/19/2016', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (29, 'Osmund', 'Pardoe', 'Cossem', str_to_date('04/06/1969', '%c/%d/%Y'), 'M', 'SENATOR', 26150, 1, str_to_date('1/14/2010', '%c/%d/%Y'), str_to_date('7/18/2008', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (30, 'Pearline', 'Buckwell', 'Gaven', str_to_date('08/07/1946', '%c/%d/%Y'), 'F', 'SENATOR', 36310, 2, str_to_date('5/17/2008', '%c/%d/%Y'), str_to_date('6/18/2015', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (31, 'Laurie', 'Creigan', 'Deek', str_to_date('03/31/1970', '%c/%d/%Y'), 'M', 'SENATOR', 35736, 0, str_to_date('6/6/2016', '%c/%d/%Y'), str_to_date('1/29/2004', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (32, 'Joann', 'Featherstonhalgh', str_to_date('Henrys', '01/15/1956', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 32623, 0, str_to_date('5/12/2011', '%c/%d/%Y'), str_to_date('2/18/2018', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (33, 'Ilene', 'Duthy', 'Ballston', str_to_date('08/21/1961', '%c/%d/%Y'), 'F', 'SENATOR', 31429, 2, str_to_date('10/29/2005', '%c/%d/%Y'), str_to_date('2/21/2008', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (34, 'Emmery', 'Strutt', 'Guyon', str_to_date('08/08/1959', '%c/%d/%Y'), 'M', 'SENATOR', 33879, 1, str_to_date('10/3/2010', '%c/%d/%Y'), str_to_date('5/8/2012', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (35, 'Portie', 'Farquar', 'Yitzhakov', str_to_date('01/21/1932', '%c/%d/%Y'), 'M', 'SENATOR', 26512, 1, str_to_date('3/19/2014', '%c/%d/%Y'), str_to_date('9/2/2006', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (36, 'Ruperto', 'Fort', 'Coats', str_to_date('09/13/1962', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 34347, 2, str_to_date('1/3/2014', '%c/%d/%Y'), str_to_date('7/11/2015', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (37, 'Odelinda', 'Standen', 'Sambidge', str_to_date('08/15/1949', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 20009, 2, str_to_date('2/6/2009', '%c/%d/%Y'), str_to_date('9/26/2011', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (38, 'Alexis', 'Crayker', 'Coltart', str_to_date('04/30/1966', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 29801, 1, str_to_date('10/20/2014', '%c/%d/%Y'), str_to_date('1/18/2008', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (39, 'Ardelle', 'Tows', 'Dimitrov', str_to_date('07/07/1956', '%c/%d/%Y'), 'F', 'SENATOR', 23597, 1, str_to_date('3/15/2012', '%c/%d/%Y'), str_to_date('4/27/2006', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (40, 'Bradford', 'Chalcraft', 'Farndale', str_to_date('03/30/1970', '%c/%d/%Y'), 'M', 'SENATOR', 11878, 0, str_to_date('3/6/2006', '%c/%d/%Y'), str_to_date('12/19/2016', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (41, 'Myrle', 'Joyner', 'Olyfant', str_to_date('05/21/1933', '%c/%d/%Y'), 'F', 'SENATOR', 19837, 0, str_to_date('7/23/2008', '%c/%d/%Y'), str_to_date('11/19/2012', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (42, 'Karlotte', 'Lucock', 'Lusted', str_to_date('01/21/1967', '%c/%d/%Y'), 'F', 'SENATOR', 35931, 0, str_to_date('3/4/2010', '%c/%d/%Y'), str_to_date('12/26/2012', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (43, 'Eddy', 'Fyndon', 'Astles', str_to_date('09/15/1942', '%c/%d/%Y'), 'M', 'SENATOR', 36312, 1, str_to_date('5/21/2015', str_to_date('5/31/2018', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (44, 'Crissy', 'Lukianovich', 'Katte', str_to_date('01/30/1934', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 18194, 0, str_to_date('8/3/2009', '%c/%d/%Y'), str_to_date('8/28/2006', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (45, 'Barbey', 'Sweeney', 'Canfer', str_to_date('01/15/1970', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 36438, 0, str_to_date('10/10/2007', '%c/%d/%Y'), str_to_date('1/1/2010', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (46, 'Aundrea', 'Benton', 'Posvner', str_to_date('11/25/1968', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 16417, 0, str_to_date('6/4/2008', '%c/%d/%Y'), str_to_date('1/13/2011', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (47, 'Rolf', 'Canning', 'Crowden', str_to_date('03/13/1932', '%c/%d/%Y'), 'M', 'SENATOR', 24591, 1, str_to_date('2/8/2005', '%c/%d/%Y'), str_to_date('12/19/2007', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (48, 'Brockie', 'Gaw', 'Bagley', str_to_date('10/28/1964', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 11781, 2, str_to_date('12/27/2004', '%c/%d/%Y'), str_to_date('7/16/2011', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (49, 'Fran', 'Broadberrie', 'Hamelyn', str_to_date('03/09/1935', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 38082, 0, str_to_date('10/29/2014', '%c/%d/%Y'), str_to_date('9/26/2006', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (50, 'Olin', 'Robardey', 'Leser', str_to_date('05/03/1931', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 15614, 2, str_to_date('1/9/2009', '%c/%d/%Y'), str_to_date('8/8/2008', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (51, 'Barbie', 'Fancott', 'Brosenius', str_to_date('12/11/1937', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 14681, 2, str_to_date('10/7/2005', '%c/%d/%Y'), str_to_date('1/31/2014', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (52, 'Lenette', 'Burghill', 'Schruyer', str_to_date('06/12/1967', '%c/%d/%Y'), '%c/%d/%Y'), 'F', 'SENATOR', 23547, 0, str_to_date('2/24/2008', '%c/%d/%Y'), str_to_date('1/17/2004', '%c/%d/%Y'), '%c/%d/%Y'), '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (53, 'Zelda', 'Wyon', 'Melross', str_to_date('04/08/1957', '%c/%d/%Y'), 'F', 'SENATOR', 29861, 1, str_to_date('1/31/2006', '%c/%d/%Y'), '%c/%d/%Y'), str_to_date('1/15/2011', '%c/%d/%Y'), '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (54, 'Wilhelm', 'Lanston', 'Delph', str_to_date('02/20/1943', '%c/%d/%Y'), 'M', 'SENATOR', 32669, 2, str_to_date('5/3/2014', '%c/%d/%Y'), str_to_date('3/28/2017', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (55, 'Emmalyn', 'Biddlestone', 'Seckington', str_to_date('06/18/1965', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 23417, 2, str_to_date('9/29/2007', '%c/%d/%Y'), '%c/%d/%Y'), str_to_date('4/26/2007', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (56, 'Augustin', 'Jewers', 'Ellison', str_to_date('03/04/1933', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 21305, 0, str_to_date('5/31/2005', '%c/%d/%Y'), str_to_date('1/13/2007', '%c/%d/%Y'), '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (57, 'Martyn', 'Stickel', 'Napoli', str_to_date('12/07/1952', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 10226, 0, str_to_date('10/29/2013', '%c/%d/%Y'), '%c/%d/%Y'), str_to_date('4/24/2004', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (58, 'Hyacinth', 'Radin', 'Sacks', str_to_date('12/06/1964', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 27809, 0, str_to_date('11/24/2011', '%c/%d/%Y'), str_to_date('9/22/2016', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (59, 'Kerby', 'Stollmeier', 'Steart', str_to_date('12/06/1964', '%c/%d/%Y'), 'M', 'SENATOR', 14350, 1, str_to_date('4/3/2007', '%c/%d/%Y'), str_to_date('6/11/2019');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (60, 'Allys', 'Sneaker', 'Wadworth', str_to_date('11/16/1940', '%c/%d/%Y'), 'F', 'SENATOR', 30707, 0, str_to_date('1/23/2014', '%c/%d/%Y'), str_to_date('1/4/2016');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (61, 'Cordy', 'Farrance', 'Dumphries', str_to_date('09/11/1936', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 35583, 1, str_to_date('3/25/2004', '%c/%d/%Y'), str_to_date('7/31/2008', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (62, 'Mortie', 'Grzegorzewicz', 'Rosbrough', str_to_date('08/31/1960', '%c/%d/%Y'), 'M', 'SENATOR', 39532, 0, str_to_date('5/21/2006', '%c/%d/%Y'), str_to_date('8/2/2018', '%c/%d/%Y'), '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (63, 'Benedikt', 'Grestie', 'Sandeford', str_to_date('04/04/1967', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 16126, 0, str_to_date('6/26/2008', '%c/%d/%Y'), str_to_date('10/28/2015', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (64, 'Maison', 'Goodings', 'Motton', str_to_date('03/18/1937', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 34476, 1, str_to_date('6/2/2010', '%c/%d/%Y'), str_to_date('8/26/2012', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (65, 'Kin', 'Gilderoy', 'Divall', str_to_date('11/05/1960', '%c/%d/%Y'), 'M', 'SENATOR', 18091, 1, str_to_date('7/26/2008', '%c/%d/%Y'), str_to_date('10/12/2008', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (66, 'Burnaby', 'Hoffmann', 'Dodshun', str_to_date('04/15/1967', '%c/%d/%Y'), 'M', 'SENATOR', 23746, 0, str_to_date('6/12/2015', '%c/%d/%Y'), str_to_date('1/25/2008', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (67, 'Stearne', 'Antonsen', 'Crystal', str_to_date('04/30/1954', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 14026, 1, str_to_date('1/8/2008', '%c/%d/%Y'), str_to_date('7/18/2015', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (68, 'Hillyer', 'Stebbing', 'Winwright', str_to_date('05/20/1943', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 22483, 0, str_to_date('3/25/2006', '%c/%d/%Y'), str_to_date('1/25/2017', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (69, 'Riccardo', 'Torrejon', 'Keeton', str_to_date('05/09/1964', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 27647, 0, str_to_date('9/26/2012', '%c/%d/%Y'), '%c/%d/%Y'), str_to_date('8/16/2010', '%c/%d/%Y'), '%c/%d/%Y'), '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (70, 'Donelle', 'Kerner', 'Leban', str_to_date('11/29/1962', '%c/%d/%Y'), 'F', 'SENATOR', 27195, 2, str_to_date('11/23/2014', '%c/%d/%Y'), str_to_date('3/1/2017', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (71, 'Dennie', 'Dunthorne', 'Nicklen', str_to_date('02/25/1938', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 36656, 2, str_to_date('1/25/2013', '%c/%d/%Y'), str_to_date('12/5/2018', '%c/%d/%Y'), '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (72, 'Conny', 'Cleary', 'Flode', str_to_date('07/18/1952', '%c/%d/%Y'), 'M', 'SENATOR', 12461, 2, str_to_date('5/20/2007', '%c/%d/%Y'), str_to_date('2/4/2004', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (73, 'Carolin', 'Johnston', 'Schoenleiter', str_to_date('11/26/1962', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 25606, 1, str_to_date('2/8/2013', '%c/%d/%Y'), str_to_date('3/26/2007', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (74, 'Meridith', 'Kosel', 'Rilston', str_to_date('03/11/1943', '%c/%d/%Y'), 'F', 'SENATOR', 10797, 2, str_to_date('12/16/2008', '%c/%d/%Y'), str_to_date('9/13/2019', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (75, 'Verena', 'Prater', 'Gronowe', str_to_date('05/02/1938', '%c/%d/%Y'), 'F', 'SENATOR', 20213, 1, str_to_date('3/23/2015', '%c/%d/%Y'), str_to_date('7/29/2018', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (76, 'Sherlocke', 'Tetlow', 'Ficken', str_to_date('10/09/1932', '%c/%d/%Y'), 'M', 'SENATOR', 38354, 1, str_to_date('8/4/2004', '%c/%d/%Y'), str_to_date('7/8/2015', '%c/%d/%Y'), '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (77, 'Terrye', 'Bridie', 'Emblen', str_to_date('12/04/1961', '%c/%d/%Y'), 'F', 'SENATOR', 20499, 0, str_to_date('12/4/2012', '%c/%d/%Y'), str_to_date('7/11/2005', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (78, 'Nikolai', 'Pach', 'Escala', str_to_date('11/13/1961', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 16668, 2, str_to_date('3/25/2014', str_to_date('11/20/2007', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (79, 'Jolyn', 'Stebbin', 'Roos', str_to_date('04/01/1946', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 17171, 1, str_to_date('8/22/2007', '%c/%d/%Y'), str_to_date('9/18/2011', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (80, 'Archer', 'Bruno', 'Kleinberer', str_to_date('05/13/1956', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 17688, 0, str_to_date('4/12/2005', '%c/%d/%Y'), str_to_date('12/7/2013', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (81, 'Jourdain', 'Lehrer', 'O''Bradain', str_to_date('12/29/1940', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 21149, 2, str_to_date('5/29/2014', '%c/%d/%Y'), str_to_date('12/27/2018', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (82, 'Kimberlyn', 'Hellwich', 'Minichi', str_to_date('02/28/1943', '%c/%d/%Y'), 'F', 'SENATOR', 24180, 2, str_to_date('5/27/2009', '%c/%d/%Y'), str_to_date('5/1/2008', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (83, 'Prudi', 'Baish', 'Godfree', str_to_date('08/27/1933', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 10592, 2, str_to_date('4/29/2011', '%c/%d/%Y'), str_to_date('4/25/2017', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (84, 'Cleon', 'Aristide', 'Itzchaki', str_to_date('05/18/1965', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 10400, 1, str_to_date('11/8/2013', '%c/%d/%Y'), str_to_date('12/23/2011', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (85, 'Lulu', 'McNee', 'McQuorkell', str_to_date('08/27/1940', '%c/%d/%Y'), 'F', 'SENATOR', 11445, 1, str_to_date('7/5/2008', '%c/%d/%Y'), str_to_date('1/17/2013', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (86, 'Nanine', 'Riquet', 'Manning', str_to_date('08/14/1932', '%c/%d/%Y'), 'F', 'SENATOR', 36560, 0, str_to_date('5/22/2009', '%c/%d/%Y'), str_to_date('3/1/2018', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (87, 'Frederic', 'Cotmore', 'McVane', str_to_date('07/04/1955', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 27375, 0, str_to_date('12/12/2014', '%c/%d/%Y'), str_to_date('4/5/2015', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (88, 'Bettye', 'McClintock', 'Ladewig', str_to_date('06/13/1957', '%c/%d/%Y'), 'F', 'SENATOR', 15871, 0, str_to_date('10/2/2012', '%c/%d/%Y'), str_to_date('7/6/2007', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (89, 'Dell', 'Turle', 'Argo', str_to_date('08/09/1967', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 25066, 1, str_to_date('7/23/2016', '%c/%d/%Y'), str_to_date('7/31/2006', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (90, 'Hewett', 'Oakenfall', 'Wiersma', str_to_date('11/03/1969', '%c/%d/%Y'), 'M', 'SENATOR', 19150, 2, str_to_date('9/9/2007', '%c/%d/%Y'), str_to_date('6/15/2004', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (91, 'Sarena', 'Laughlan', 'Rentcome', str_to_date('02/08/1937', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 23925, 0, str_to_date('5/12/2009', '%c/%d/%Y'), str_to_date('1/5/2014', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (92, 'Merwin', 'Eads', 'Brameld', str_to_date('05/20/1967', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 15199, 0, str_to_date('10/29/2006', '%c/%d/%Y'), str_to_date('8/21/2018', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (93, 'Johannes', 'Whyler', 'Tootal', str_to_date('12/15/1960', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 39559, 2, str_to_date('6/8/2012', '%c/%d/%Y'), str_to_date('6/3/2005', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (94, 'Evin', 'Macro', 'Chastney', str_to_date('04/03/1955', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 39538, 0, str_to_date('3/14/2013', '%c/%d/%Y'), str_to_date('9/23/2008', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (95, 'Chilton', 'Radbond', 'Draisey', str_to_date('02/27/1951', '%c/%d/%Y'), 'M', 'SENATOR', 14543, 0, str_to_date('11/5/2011', '%c/%d/%Y'), str_to_date('11/6/2007', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (96, 'Durward', 'Gloyens', 'Bidewell', str_to_date('10/07/1965', '%c/%d/%Y'), 'M', 'SENATOR', 33409, 2, str_to_date('3/19/2005', '%c/%d/%Y'), str_to_date('10/24/2016', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (97, 'Paulette', 'Varsey', 'Jollands', str_to_date('05/19/1937', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 27773, 1, str_to_date('4/12/2012', '%c/%d/%Y'), str_to_date('4/16/2008', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (98, 'Maren', 'Jobbins', 'Dodgshon', str_to_date('05/18/1948', '%c/%d/%Y'), 'F', 'SENATOR', 35510, 1, str_to_date('12/14/2012', '%c/%d/%Y'), str_to_date('12/1/2016', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (99, 'Lona', 'Belch', 'Bell', str_to_date('11/14/1967', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 36251, 2, str_to_date('1/28/2007', '%c/%d/%Y'), str_to_date('4/25/2012', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (100, 'Fowler', 'Stainer', 'Poor', str_to_date('06/20/1930', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 36570, 0, str_to_date('6/24/2005', '%c/%d/%Y'), str_to_date('4/15/2014', '%c/%d/%Y'));

-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (1, 'sem mauris', 'vestibulum ante ipsum', 'HouseBill', 'Provincial', 'Passed', '2nd', '6/23/2016');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (2, 'eros vestibulum ac est lacinia nisi', 'commodo vulputate justo in', 'SenateBill', 'Provincial', 'Pending', '3rd', '4/29/2009');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (3, 'sapien iaculis congue vivamus metus arcu adipiscing', 'mauris sit amet eros suspendisse accumsan tortor', 'HouseBill', 'Provincial', 'Passed', '3rd', '11/19/2009');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (4, 'varius', 'mattis pulvinar nulla pede ullamcorper augue', 'HouseBill', 'National', 'Passed', '3rd', '6/16/2013');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (5, 'in hac habitasse platea', 'arcu sed augue aliquam erat volutpat', 'SenateBill', 'Municipal', 'Pending', '2nd', '12/2/2014');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (6, 'volutpat sapien arcu sed augue aliquam erat volutpat', 'mauris vulputate elementum nullam varius nulla facilisi', 'SenateBill', 'Municipal', 'Passed','1st', '8/24/2012');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (7, 'et magnis dis parturient', 'ac neque duis bibendum morbi non quam', 'HouseBill', 'National', 'Pending', '2nd', '8/8/2009');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (8, 'turpis', 'nunc commodo placerat praesent blandit nam nulla', 'HouseBill', 'Provincial', 'Passed', '1st', '5/21/2011');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (9, 'habitasse', 'et ultrices posuere cubilia curae donec pharetra', 'SenateBill', 'National', 'Passed', '2nd', '5/28/2008');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (10, 'dui luctus rutrum', 'libero convallis eget eleifend', 'SenateBill', 'Municipal', 'Passed', '3rd', '9/14/2016');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (11, 'dui proin leo odio', 'ut odio cras', 'SenateBill', 'National', 'Pending', '1st', '7/5/2014');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (12, 'feugiat non pretium quis lectus', 'suscipit a feugiat et eros vestibulum ac', 'HouseBill', 'Provincial', 'Pending', '1st', '6/22/2004');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (13, 'consectetuer adipiscing elit proin', 'congue risus semper porta volutpat quam', 'SenateBill', 'Provincial', 'Pending', '2nd', '7/22/2009');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (14, 'et magnis', 'aliquam erat volutpat in congue etiam justo', 'SenateBill', 'National', 'Pending', '1st', '12/4/2007');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (15, 'enim', 'suspendisse ornare consequat lectus', 'SenateBill', 'National', 'Pending', '3rd', '7/15/2005');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (16, 'ac nibh fusce lacus purus aliquet at', 'eleifend donec ut', 'SenateBill', 'Provincial', 'Passed', '3rd', '11/30/2014');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (17, 'quis lectus suspendisse potenti in eleifend quam a', 'eu tincidunt in leo', 'SenateBill', 'Municipal', 'Passed', '1st', '8/31/2015');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (18, 'a ipsum integer', 'volutpat erat', 'SenateBill', 'Provincial', 'Passed', '2nd', '7/24/2006');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (19, 'eget semper rutrum nulla nunc purus phasellus in', 'vestibulum quam', 'SenateBill', 'Provincial', 'Passed', '2nd', '2/5/2004');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (20, 'faucibus accumsan odio curabitur convallis duis', 'at nulla suspendisse potenti cras in purus', 'HouseBill', 'Provincial', 'Passed', '1st', '2/22/2016');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (21, 'vel augue vestibulum rutrum', 'velit eu est congue elementum in', 'SenateBill', 'Provincial', 'Pending', '3rd', '9/18/2008');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (22, 'praesent', 'at vulputate vitae nisl aenean lectus pellentesque eget', 'HouseBill', 'Municipal', 'Passed', '2nd', '3/10/2013');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (23, 'nulla pede ullamcorper augue a suscipit nulla elit', 'aenean auctor gravida sem praesent', 'HouseBill', 'National', 'Pending', '2nd', '2/7/2007');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (24, 'vestibulum vestibulum ante ipsum primis', 'aliquam augue quam', 'HouseBill', 'National', 'Passed', '1st', '12/15/2004');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (25, 'sit amet eleifend pede libero quis orci nullam', 'platea dictumst aliquam augue quam sollicitudin vitae consectetuer', 'HouseBill', 'Provincial', 'Passed', '3rd', '3/17/2012');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (26, 'nascetur ridiculus', 'donec semper sapien a', 'SenateBill', 'Provincial', 'Passed', '3rd', '6/7/2014');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (27, 'aenean', 'ut volutpat sapien arcu', 'SenateBill', 'Provincial', 'Pending', '1st', '9/1/2014');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (28, 'molestie', 'nulla ac enim in tempor turpis', 'HouseBill', 'Municipal', 'Passed', '1st', '7/4/2015');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (29, 'sollicitudin vitae consectetuer eget rutrum at', 'duis at', 'HouseBill', 'National', 'Pending', '2nd', '4/8/2016');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (30, 'quam', 'erat eros viverra eget congue eget semper', 'SenateBill', 'Provincial', 'Passed', '2nd', '1/12/2011');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (31, 'mollis molestie lorem quisque', 'faucibus orci', 'SenateBill', 'National', 'Passed', '2nd', '5/6/2017');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (32, 'varius ut', 'convallis nulla neque libero convallis eget eleifend', 'HouseBill', 'Provincial', 'Pending', '1st', '11/2/2017');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (33, 'orci luctus et ultrices posuere cubilia', 'nec dui luctus rutrum nulla', 'SenateBill', 'National', 'Pending', '2nd', '11/24/2011');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (34, 'tempus vivamus in felis', 'nulla', 'SenateBill', 'Municipal', 'Passed', '1st', '4/28/2015');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (35, 'vitae nisi nam ultrices libero non', 'lectus suspendisse', 'HouseBill', 'Municipal', 'Passed', '3rd', '12/5/2012');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (36, 'imperdiet sapien urna pretium nisl ut volutpat', 'neque sapien placerat ante nulla justo aliquam quis', 'HouseBill', 'Provincial', 'Passed', '2nd', '8/25/2011');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (37, 'pulvinar lobortis est', 'nisi at nibh', 'SenateBill', 'Provincial', 'Pending', '2nd', '8/9/2017');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (38, 'auctor', 'sapien dignissim vestibulum vestibulum ante', 'SenateBill', 'Provincial', 'Passed', '1st', '3/10/2004');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (39, 'luctus', 'elit proin risus praesent lectus vestibulum quam', 'HouseBill', 'Municipal', 'Pending', '1st', '8/21/2007');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (40, 'gravida sem praesent id massa id nisl venenatis', 'fringilla rhoncus mauris enim leo rhoncus sed vestibulum', 'SenateBill', 'Provincial', 'Passed', '1st', '1/18/2009');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (41, 'sit amet sapien', 'primis in faucibus orci', 'SenateBill', 'Municipal', 'Passed', '2nd', '7/19/2009');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (42, 'nibh fusce', 'eget orci vehicula', 'SenateBill', 'Municipal', 'Passed', '1st', '3/1/2010');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (43, 'nulla tempus vivamus in felis eu sapien cursus', 'diam cras pellentesque volutpat', 'HouseBill', 'Provincial', 'Pending', '2nd', '2/21/2004');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (44, 'vestibulum ac est', 'rutrum at lorem integer', 'HouseBill', 'Provincial', 'Passed', '1st', '6/21/2015');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (45, 'accumsan tortor quis turpis', 'nullam orci pede venenatis non sodales sed', 'SenateBill', 'National', 'Passed', '1st', '1/15/2016');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (46, 'suscipit a feugiat et eros vestibulum', 'penatibus et magnis dis parturient', 'SenateBill', 'National', 'Passed', '3rd', '5/4/2012');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (47, 'felis eu sapien cursus vestibulum proin', 'mi pede malesuada in imperdiet et commodo', 'SenateBill', 'Provincial', 'Pending', '3rd', '4/16/2015');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (48, 'sed augue aliquam erat volutpat in congue', 'nec molestie', 'SenateBill', 'Provincial', 'Passed', '2nd', '6/18/2013');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (49, 'eros', 'eget tincidunt', 'HouseBill', 'Provincial', 'Pending', '1st', '5/12/2006');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (50, 'justo lacinia', 'proin leo', 'SenateBill', 'Provincial', 'Passed', '3rd', '6/12/2014');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (51, 'justo aliquam quis turpis', 'ridiculus mus vivamus vestibulum sagittis sapien cum sociis', 'HouseBill', 'Provincial', 'Pending', '1st', '9/8/2005');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (52, 'nulla facilisi cras non velit nec', 'convallis morbi odio odio elementum eu', 'HouseBill', 'Municipal', 'Passed', '2nd', '3/31/2004');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (53, 'accumsan felis ut at', 'vestibulum ante ipsum primis in faucibus orci', 'HouseBill', 'National', 'Passed', '2nd', '6/22/2007');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (54, 'urna pretium nisl ut volutpat sapien arcu sed', 'mauris enim leo', 'SenateBill', 'Provincial', 'Pending', '2nd', '9/15/2011');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (55, 'volutpat in congue etiam justo etiam', 'sed ante vivamus tortor duis', 'SenateBill', 'Provincial', 'Passed', '2nd', '9/21/2012');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (56, 'mauris enim leo rhoncus', 'sed vel enim sit amet nunc viverra dapibus', 'HouseBill', 'Municipal', 'Pending', '3rd', '6/7/2011');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (57, 'magna vulputate', 'sollicitudin vitae consectetuer eget', 'SenateBill', 'National', 'Passed', '1st', '11/21/2015');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (58, 'id lobortis convallis tortor risus dapibus augue', 'amet cursus', 'HouseBill', 'Provincial', 'Pending', '2nd', '4/13/2016');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (59, 'pellentesque ultrices phasellus id sapien in', 'vestibulum ante ipsum primis in faucibus orci luctus', 'SenateBill', 'Municipal', 'Passed', '1st', '8/12/2015');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (60, 'gravida sem praesent id', 'nunc vestibulum ante ipsum primis', 'SenateBill', 'Provincial', 'Pending', '3rd', '1/29/2010');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (61, 'ut at dolor quis', 'eleifend pede libero quis orci nullam', 'HouseBill', 'Provincial', 'Passed', '1st', '4/15/2006');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (62, 'metus aenean fermentum donec ut mauris', 'ipsum primis in', 'HouseBill', 'Provincial', 'Passed', '2nd', '3/17/2008');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (63, 'magnis dis parturient montes nascetur ridiculus', 'elementum', 'HouseBill', 'Provincial', 'Passed', '1st', '5/13/2013');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (64, 'nulla ut erat id mauris vulputate', 'quisque arcu libero rutrum', 'HouseBill', 'Provincial', 'Passed', '3rd', '7/30/2009');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (65, 'lacus morbi quis tortor id nulla', 'id justo sit', 'SenateBill', 'Provincial', 'Passed', '2nd', '3/4/2015');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (66, 'in est', 'in faucibus orci luctus et ultrices posuere cubilia', 'HouseBill', 'Provincial', 'Pending', '1st', '9/10/2010');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (67, 'et magnis dis parturient montes nascetur ridiculus', 'sed interdum venenatis turpis enim blandit', 'HouseBill', 'Municipal', 'Passed', '1st', '3/15/2012');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (68, 'nam congue risus semper', 'leo', 'HouseBill', 'Provincial', 'Pending', '2nd', '6/19/2016');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (69, 'molestie nibh in lectus', 'elementum pellentesque quisque porta', 'HouseBill', 'Provincial', 'Pending', '2nd', '9/28/2011');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (70, 'dolor', 'phasellus id sapien in sapien iaculis', 'HouseBill', 'Provincial', 'Pending', '3rd', '3/6/2008');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (71, 'nisl duis', 'dapibus duis at velit', 'HouseBill', 'National', 'Pending', '3rd', '1/29/2005');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (72, 'quisque id justo', 'in lectus pellentesque at nulla suspendisse potenti cras', 'SenateBill', 'Provincial', 'Pending', '3rd', '9/9/2014');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (73, 'lacus morbi quis', 'curae', 'SenateBill', 'National', 'Passed', '1st', '8/13/2005');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (74, 'adipiscing molestie hendrerit', 'rhoncus dui vel sem sed sagittis nam congue', 'HouseBill', 'Provincial', 'Passed', '2nd', '10/11/2006');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (75, 'neque duis bibendum morbi non quam nec', 'ullamcorper augue a', 'HouseBill', 'Provincial', 'Pending', '3rd', '11/10/2005');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (76, 'blandit non interdum in ante vestibulum ante', 'id lobortis convallis tortor risus dapibus augue vel', 'HouseBill', 'Provincial', 'Passed', '3rd', '8/6/2013');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (77, 'sem praesent id massa id nisl', 'ut at dolor', 'SenateBill', 'Municipal', 'Passed', '3rd', '10/7/2014');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (78, 'non pretium quis', 'id nulla ultrices aliquet maecenas leo', 'HouseBill', 'Municipal', 'Pending', '3rd', '10/3/2014');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (79, 'eget orci vehicula condimentum', 'nulla quisque arcu libero rutrum ac', 'HouseBill', 'Municipal', 'Passed', '3rd', '2/17/2007');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (80, 'ac lobortis', 'rutrum ac lobortis', 'SenateBill', 'Provincial', 'Passed', '2nd', '3/13/2007');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (81, 'at diam nam tristique tortor eu pede', 'blandit nam nulla integer', 'HouseBill', 'Provincial', 'Pending', '3rd', '6/5/2008');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (82, 'quis lectus suspendisse potenti', 'consequat', 'HouseBill', 'Provincial', 'Passed', '1st', '9/19/2012');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (83, 'in est', 'orci luctus et ultrices', 'HouseBill', 'Provincial', 'Pending', '2nd', '12/29/2007');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (84, 'condimentum neque', 'sollicitudin vitae consectetuer eget rutrum', 'SenateBill', 'Provincial', 'Passed', '1st', '10/7/2005');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (85, 'vivamus vestibulum sagittis', 'nec dui', 'HouseBill', 'National', 'Passed', '3rd', '6/19/2012');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (86, 'nascetur ridiculus mus etiam vel', 'est quam pharetra magna ac consequat metus sapien', 'SenateBill', 'Municipal', 'Passed', '2nd', '12/7/2007');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (87, 'dis parturient montes nascetur ridiculus', 'vestibulum sit amet', 'SenateBill', 'Provincial', 'Pending', '3rd', '5/14/2016');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (88, 'morbi', 'nulla sed accumsan felis', 'HouseBill', 'Provincial', 'Pending', '2nd', '9/17/2014');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (89, 'nec euismod scelerisque quam turpis adipiscing', 'consequat varius', 'SenateBill', 'Provincial', 'Passed', '1st', '3/19/2009');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (90, 'ac consequat', 'mauris eget massa tempor convallis', 'SenateBill', 'National', 'Passed', '1st', '4/4/2007');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (91, 'amet consectetuer adipiscing elit proin interdum', 'duis', 'HouseBill', 'National', 'Pending', '2nd', '4/13/2008');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (92, 'nec nisi volutpat eleifend donec ut dolor', 'ipsum ac tellus semper interdum mauris', 'HouseBill', 'Municipal', 'Pending', '3rd', '11/18/2007');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (93, 'vulputate', 'turpis', 'HouseBill', 'Municipal', 'Pending', '3rd', '11/17/2005');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (94, 'erat quisque', 'metus aenean fermentum donec ut mauris', 'HouseBill', 'National', 'Passed', '1st', '2/8/2008');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (95, 'morbi quis tortor id', 'mattis pulvinar nulla pede ullamcorper augue a', 'SenateBill', 'Municipal', 'Passed', '1st', '4/1/2005');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (96, 'augue', 'elit proin risus praesent lectus vestibulum', 'SenateBill', 'National', 'Pending', '2nd', '12/8/2006');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (97, 'rhoncus', 'imperdiet sapien urna pretium nisl ut volutpat', 'SenateBill', 'Provincial', 'Passed', '1st', '6/24/2009');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (98, 'iaculis diam', 'nullam molestie nibh in lectus pellentesque at nulla', 'SenateBill', 'National', 'Passed', '3rd', '7/4/2007');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (99, 'sed interdum venenatis', 'maecenas pulvinar lobortis est phasellus sit', 'SenateBill', 'Municipal', 'Passed', '1st', '9/21/2012');
-- insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (100, 'phasellus id sapien in sapien iaculis congue', 'libero quis orci nullam molestie nibh in lectus', 'SenateBill', 'National', 'Passed', '3rd', '5/24/2004');

insert into bill_author (billno, empid) values (84, 28);
insert into bill_author (billno, empid) values (31, 22);
insert into bill_author (billno, empid) values (65, 98);
insert into bill_author (billno, empid) values (21, 66);
insert into bill_author (billno, empid) values (23, 38);
insert into bill_author (billno, empid) values (44, 93);
insert into bill_author (billno, empid) values (2, 6);
insert into bill_author (billno, empid) values (50, 51);
insert into bill_author (billno, empid) values (5, 92);
insert into bill_author (billno, empid) values (68, 29);
insert into bill_author (billno, empid) values (29, 57);
insert into bill_author (billno, empid) values (75, 29);
insert into bill_author (billno, empid) values (79, 9);
insert into bill_author (billno, empid) values (68, 69);
insert into bill_author (billno, empid) values (55, 91);
insert into bill_author (billno, empid) values (14, 12);
insert into bill_author (billno, empid) values (73, 77);
insert into bill_author (billno, empid) values (80, 5);
insert into bill_author (billno, empid) values (67, 31);
insert into bill_author (billno, empid) values (4, 44);
insert into bill_author (billno, empid) values (77, 37);
insert into bill_author (billno, empid) values (78, 60);
insert into bill_author (billno, empid) values (71, 89);
insert into bill_author (billno, empid) values (87, 28);
insert into bill_author (billno, empid) values (1, 81);
insert into bill_author (billno, empid) values (21, 100);
insert into bill_author (billno, empid) values (11, 78);
insert into bill_author (billno, empid) values (46, 11);
insert into bill_author (billno, empid) values (28, 2);
insert into bill_author (billno, empid) values (58, 47);
insert into bill_author (billno, empid) values (20, 40);
insert into bill_author (billno, empid) values (93, 89);
insert into bill_author (billno, empid) values (48, 86);
insert into bill_author (billno, empid) values (95, 55);
insert into bill_author (billno, empid) values (28, 48);
insert into bill_author (billno, empid) values (76, 27);
insert into bill_author (billno, empid) values (10, 23);
insert into bill_author (billno, empid) values (82, 10);
insert into bill_author (billno, empid) values (61, 11);
insert into bill_author (billno, empid) values (75, 54);
insert into bill_author (billno, empid) values (12, 28);
insert into bill_author (billno, empid) values (43, 12);
insert into bill_author (billno, empid) values (57, 18);
insert into bill_author (billno, empid) values (77, 30);
insert into bill_author (billno, empid) values (56, 40);
insert into bill_author (billno, empid) values (60, 29);
insert into bill_author (billno, empid) values (52, 68);
insert into bill_author (billno, empid) values (42, 67);
insert into bill_author (billno, empid) values (78, 99);
insert into bill_author (billno, empid) values (24, 46);
insert into bill_author (billno, empid) values (12, 69);
insert into bill_author (billno, empid) values (50, 45);
insert into bill_author (billno, empid) values (18, 54);
insert into bill_author (billno, empid) values (37, 88);
insert into bill_author (billno, empid) values (20, 27);
insert into bill_author (billno, empid) values (97, 90);
insert into bill_author (billno, empid) values (87, 100);
insert into bill_author (billno, empid) values (3, 81);
insert into bill_author (billno, empid) values (66, 92);
insert into bill_author (billno, empid) values (27, 65);
insert into bill_author (billno, empid) values (39, 35);
insert into bill_author (billno, empid) values (65, 98);
insert into bill_author (billno, empid) values (34, 6);
insert into bill_author (billno, empid) values (42, 99);
insert into bill_author (billno, empid) values (60, 45);
insert into bill_author (billno, empid) values (92, 19);
insert into bill_author (billno, empid) values (47, 41);
insert into bill_author (billno, empid) values (85, 16);
insert into bill_author (billno, empid) values (72, 29);
insert into bill_author (billno, empid) values (18, 90);
insert into bill_author (billno, empid) values (16, 44);
insert into bill_author (billno, empid) values (14, 84);
insert into bill_author (billno, empid) values (17, 77);
insert into bill_author (billno, empid) values (79, 41);
insert into bill_author (billno, empid) values (20, 84);
insert into bill_author (billno, empid) values (59, 30);
insert into bill_author (billno, empid) values (39, 95);
insert into bill_author (billno, empid) values (59, 99);
insert into bill_author (billno, empid) values (1, 72);
insert into bill_author (billno, empid) values (87, 96);
insert into bill_author (billno, empid) values (86, 75);
insert into bill_author (billno, empid) values (32, 100);
insert into bill_author (billno, empid) values (74, 63);
insert into bill_author (billno, empid) values (73, 6);
insert into bill_author (billno, empid) values (63, 30);
insert into bill_author (billno, empid) values (36, 55);
insert into bill_author (billno, empid) values (50, 96);
insert into bill_author (billno, empid) values (3, 10);
insert into bill_author (billno, empid) values (37, 54);
insert into bill_author (billno, empid) values (97, 81);
insert into bill_author (billno, empid) values (31, 36);
insert into bill_author (billno, empid) values (84, 26);
insert into bill_author (billno, empid) values (68, 62);
insert into bill_author (billno, empid) values (68, 86);
insert into bill_author (billno, empid) values (65, 25);
insert into bill_author (billno, empid) values (20, 32);
insert into bill_author (billno, empid) values (23, 32);
insert into bill_author (billno, empid) values (47, 10);
insert into bill_author (billno, empid) values (74, 59);
insert into bill_author (billno, empid) values (14, 31);
insert into bill_author (billno, empid) values (36, 4);
insert into bill_author (billno, empid) values (97, 72);
insert into bill_author (billno, empid) values (6, 44);
insert into bill_author (billno, empid) values (2, 26);
insert into bill_author (billno, empid) values (32, 96);
insert into bill_author (billno, empid) values (38, 84);
insert into bill_author (billno, empid) values (12, 86);
insert into bill_author (billno, empid) values (74, 35);
insert into bill_author (billno, empid) values (94, 78);
insert into bill_author (billno, empid) values (86, 25);
insert into bill_author (billno, empid) values (54, 86);
insert into bill_author (billno, empid) values (31, 5);
insert into bill_author (billno, empid) values (55, 91);
insert into bill_author (billno, empid) values (26, 12);
insert into bill_author (billno, empid) values (88, 25);
insert into bill_author (billno, empid) values (14, 77);
insert into bill_author (billno, empid) values (63, 95);
insert into bill_author (billno, empid) values (73, 67);
insert into bill_author (billno, empid) values (99, 29);
insert into bill_author (billno, empid) values (46, 15);
insert into bill_author (billno, empid) values (74, 86);
insert into bill_author (billno, empid) values (36, 82);
insert into bill_author (billno, empid) values (25, 76);
insert into bill_author (billno, empid) values (88, 10);
insert into bill_author (billno, empid) values (1, 29);
insert into bill_author (billno, empid) values (4, 59);
insert into bill_author (billno, empid) values (31, 23);
insert into bill_author (billno, empid) values (81, 68);
insert into bill_author (billno, empid) values (61, 64);
insert into bill_author (billno, empid) values (9, 29);
insert into bill_author (billno, empid) values (7, 19);
insert into bill_author (billno, empid) values (97, 47);
insert into bill_author (billno, empid) values (97, 44);
insert into bill_author (billno, empid) values (6, 90);
insert into bill_author (billno, empid) values (22, 18);
insert into bill_author (billno, empid) values (64, 90);
insert into bill_author (billno, empid) values (52, 77);
insert into bill_author (billno, empid) values (77, 59);
insert into bill_author (billno, empid) values (70, 29);
insert into bill_author (billno, empid) values (6, 74);
insert into bill_author (billno, empid) values (55, 26);
insert into bill_author (billno, empid) values (93, 66);
insert into bill_author (billno, empid) values (97, 57);
insert into bill_author (billno, empid) values (17, 43);
insert into bill_author (billno, empid) values (64, 24);
insert into bill_author (billno, empid) values (60, 19);
insert into bill_author (billno, empid) values (34, 29);
insert into bill_author (billno, empid) values (42, 5);
insert into bill_author (billno, empid) values (33, 35);
insert into bill_author (billno, empid) values (5, 54);

insert into bill_subject (billno, subject) values (55, '');
insert into bill_subject (billno, subject) values (80, '');
insert into bill_subject (billno, subject) values (88, '');
insert into bill_subject (billno, subject) values (74, '');
insert into bill_subject (billno, subject) values (48, '');
insert into bill_subject (billno, subject) values (21, '');
insert into bill_subject (billno, subject) values (2, '');
insert into bill_subject (billno, subject) values (12, '');
insert into bill_subject (billno, subject) values (28, '');
insert into bill_subject (billno, subject) values (67, '');
insert into bill_subject (billno, subject) values (8, '');
insert into bill_subject (billno, subject) values (19, '');
insert into bill_subject (billno, subject) values (100, '');
insert into bill_subject (billno, subject) values (49, '');
insert into bill_subject (billno, subject) values (77, '');
insert into bill_subject (billno, subject) values (13, '');
insert into bill_subject (billno, subject) values (31, '');
insert into bill_subject (billno, subject) values (26, '');
insert into bill_subject (billno, subject) values (65, '');
insert into bill_subject (billno, subject) values (14, '');
insert into bill_subject (billno, subject) values (24, '');
insert into bill_subject (billno, subject) values (60, '');
insert into bill_subject (billno, subject) values (71, '');
insert into bill_subject (billno, subject) values (74, '');
insert into bill_subject (billno, subject) values (36, '');
insert into bill_subject (billno, subject) values (91, '');
insert into bill_subject (billno, subject) values (54, '');
insert into bill_subject (billno, subject) values (26, '');
insert into bill_subject (billno, subject) values (6, '');
insert into bill_subject (billno, subject) values (77, '');
insert into bill_subject (billno, subject) values (50, '');
insert into bill_subject (billno, subject) values (86, '');
insert into bill_subject (billno, subject) values (40, '';
insert into bill_subject (billno, subject) values (71, '');
insert into bill_subject (billno, subject) values (12, '');
insert into bill_subject (billno, subject) values (62, '');
insert into bill_subject (billno, subject) values (14, '');
insert into bill_subject (billno, subject) values (77, '');
insert into bill_subject (billno, subject) values (49, '');
insert into bill_subject (billno, subject) values (17, '');
insert into bill_subject (billno, subject) values (93, '');
insert into bill_subject (billno, subject) values (39, '');
insert into bill_subject (billno, subject) values (36, '');
insert into bill_subject (billno, subject) values (14, '');
insert into bill_subject (billno, subject) values (97, '');
insert into bill_subject (billno, subject) values (50, '');
insert into bill_subject (billno, subject) values (40, '');
insert into bill_subject (billno, subject) values (100, '');
insert into bill_subject (billno, subject) values (11, '');
insert into bill_subject (billno, subject) values (36, '');
insert into bill_subject (billno, subject) values (21, '');
insert into bill_subject (billno, subject) values (17, '');
insert into bill_subject (billno, subject) values (47, '');
insert into bill_subject (billno, subject) values (30, '');
insert into bill_subject (billno, subject) values (9, '');
insert into bill_subject (billno, subject) values (25, '');
insert into bill_subject (billno, subject) values (14, '');
insert into bill_subject (billno, subject) values (79, '');
insert into bill_subject (billno, subject) values (36, '');
insert into bill_subject (billno, subject) values (26, '');
insert into bill_subject (billno, subject) values (80, '');
insert into bill_subject (billno, subject) values (31, '');
insert into bill_subject (billno, subject) values (38, '');
insert into bill_subject (billno, subject) values (40, '');
insert into bill_subject (billno, subject) values (41, '');
insert into bill_subject (billno, subject) values (94, '');
insert into bill_subject (billno, subject) values (97, '');
insert into bill_subject (billno, subject) values (67, '');
insert into bill_subject (billno, subject) values (41, '');
insert into bill_subject (billno, subject) values (12, '');
insert into bill_subject (billno, subject) values (98, '');
insert into bill_subject (billno, subject) values (49, '');
insert into bill_subject (billno, subject) values (12, '');
insert into bill_subject (billno, subject) values (57, '');
insert into bill_subject (billno, subject) values (29, '');
insert into bill_subject (billno, subject) values (52, '');
insert into bill_subject (billno, subject) values (49, '');
insert into bill_subject (billno, subject) values (95, '');
insert into bill_subject (billno, subject) values (9, '');
insert into bill_subject (billno, subject) values (5, '');
insert into bill_subject (billno, subject) values (53, '');
insert into bill_subject (billno, subject) values (10, '');
insert into bill_subject (billno, subject) values (9, '');
insert into bill_subject (billno, subject) values (55, '');
insert into bill_subject (billno, subject) values (17, '');
insert into bill_subject (billno, subject) values (85, '');
insert into bill_subject (billno, subject) values (23, '');
insert into bill_subject (billno, subject) values (90, '');
insert into bill_subject (billno, subject) values (15, '');
insert into bill_subject (billno, subject) values (57, '');
insert into bill_subject (billno, subject) values (92, '');
insert into bill_subject (billno, subject) values (46, '');
insert into bill_subject (billno, subject) values (86, '');
insert into bill_subject (billno, subject) values (55, '');
insert into bill_subject (billno, subject) values (53, '');
insert into bill_subject (billno, subject) values (15, '');
insert into bill_subject (billno, subject) values (75, '');
insert into bill_subject (billno, subject) values (74, '');
insert into bill_subject (billno, subject) values (8, '');
insert into bill_subject (billno, subject) values (68, '');
