insert into `legislator`
	values(101, 'AQUILINO KIKO', 'L', 'PIMENTEL III', str_to_date('12-13-1943', '%c-%d-%Y'), 'M', 'SENATOR', 15000, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(102, 'SERGIO', 'R', 'OSMENA', str_to_date('12-13-1943', '%c-%d-%Y'), 'M', 'SENATOR', 15000, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(103, 'MIRIAM', 'DEFENSOR', 'SANTIAGO', str_to_date('12-13-1943', '%c-%d-%Y'), 'M', 'SENATOR', 15000, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(104, 'LOREN', 'B', 'LEGARDA', str_to_date('12-13-1943', '%c-%d-%Y'), 'M', 'SENATOR', 15000, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(105, 'JINGGOY', 'P', 'EJERCITO-ESTRADA', str_to_date('12-13-1943', '%c-%d-%Y'), 'M', 'SENATOR', 15000, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(106, 'TEOFISTO', '', 'GUINGONA III', str_to_date('12-13-1943', '%c-%d-%Y'), 'M', 'SENATOR', 15000, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(107, 'RAMON', 'A', 'REVILLA JR.', str_to_date('12-13-1943', '%c-%d-%Y'), 'M', 'SENATOR', 15000, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(108, 'FRANCIS', 'G', 'ESCUDERO', str_to_date('12-13-1943', '%c-%d-%Y'), 'M', 'SENATOR', 15000, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(109, 'PIA', 'S', 'CAYETANO', str_to_date('12-13-1943', '%c-%d-%Y'), 'M', 'SENATOR', 15000, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(110, 'JUAN EDGARDO', 'M', 'ANGARA', str_to_date('12-13-1943', '%c-%d-%Y'), 'M', 'SENATOR', 15000, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(111, 'JOSEPH VICTOR', 'G', 'EJERCITO', str_to_date('12-13-1943', '%c-%d-%Y'), 'M', 'SENATOR', 15000, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(112, 'ANTONIO', 'F', 'TRILLANES', str_to_date('12-13-1943', '%c-%d-%Y'), 'M', 'SENATOR', 15000, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(113, 'GRACE', 'L', 'POE', str_to_date('12-13-1943', '%c-%d-%Y'), 'M', 'SENATOR', 15000, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(114, 'MARIA LOURDES NANCY', 'S', 'Binay', str_to_date('12-13-1943', '%c-%d-%Y'), 'M', 'SENATOR', 15000, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(115, 'MANUEL', 'M', 'LAPID', str_to_date('12-13-1943', '%c-%d-%Y'), 'M', 'SENATOR', 15000, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator`
	values(116, 'PAOLO BENIGNO', '', 'AQUINO', str_to_date('12-13-1943', '%c-%d-%Y'), 'M', 'SENATOR', 15000, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

insert into `bill`
	values(3220, 'TAX AND DUTIES EXEMPTIONS THE PRIZES OF MISS UNIVERSE PIA WURTZBACH',
		'AN ACT EXEMPTING FROM INCOME TAX, VALUE-ADDED TAX, AND IMPORT DUTIES THE WINNINGS AND/OR PRIZES OF MISS PIA ALONZO WURTZBACH AS MISS UNIVERSE 2015, AND FROM DONOR\'S TAX ANY DONATION MADE BY HER FROM SUCH WINNINGS AND/OR PRIZES',
		'SENATE BILL', 'NATIONAL', 'ARCHIVED', null, str_to_date('2016-02-03', '%Y-%c-%d'));
	insert into `bill_author` values(3220, 1);
	insert into `bill_subject` values(3220, 'VALUE-ADDED TAX');
	insert into `bill_subject` values(3220, 'TAX EXEMPTON');

insert into `bill`
	values(3221, 'ORGAN AND TISSUE DONATION ACT OF 2016',
		'AN ACT STRENGTHENING THE HUMAN ORGAN AND TISSUE DONATION AND TRANSPLANTATION PROGRAM AND PROVIDING PENALTIES FOR VIOLATION THEREOF, AMENDING FOR THIS PURPOSE REPUBLIC ACT NO. 7170, AS AMENDED, ALSO KNOWN AS THE ORGAN DONATION ACT OF 1991',
		'SENATE BILL', 'NATIONAL', 'PENDING', '2ND', str_to_date('2016-02-03', '%Y-%c-%d')) ;
	insert into `bill_author` values (3221, 3);
	insert into `bill_author` values(3221, 4);
	insert into `bill_author` values(3221, 5);
	insert into `bill_author` values(3221, 6);
	insert into `bill_subject` values(3221, 'ORGAN DONATION');

insert into `bill`
	values(3222, 'SUMMARY TITLING OF REAL PROPERTIES USED AS PUBLIC SCHOOL SITES',
		'AN ACT PROVIDING FOR THE SUMMARY TITLING OF REAL PROPERTIES USED AS PUBLIC SCHOOL SITES',
		'SENATE BILL', 'NATIONAL', 'COMM REPORT ARCHIVED', NULL, str_to_date('2016-02-03', '%Y-%c-%d'));
	insert into `bill_author` values(3222, 7);
	insert into `bill_author` values(3222, 8);
	insert into `bill_author` values(3222, 9);
	insert into `bill_author` values(3222, 4);
	insert into `bill_author` values(3222, 10);
	insert into `bill_subject` values(3222, 'REAL PROPERTIES');

insert into `bill`
	values(3223, 'PHILIPPINE HIV AND AIDS ACT',
		'AN ACT STRENGTHENING THE PHILIPPINE COMPREHENSIVE POLICY ON HIV AND AIDS PREVENTION, TREATMENT, CARE, AND SUPPORT, REPEALING FOR THE PURPOSE REPUBLIC ACT NO. 8504, OTHERWISE KNOWN AS THE PHILIPPINE AIDS PREVENTION AND CONTROL ACT OF 1998, AND APPROPRIATING FUNDS THEREFORE',
		'SENATE BILL', 'NATIONAL', 'PENDING', '2ND', str_to_date('2016-02-03', '%Y-%c-%d'));
	insert into `bill_author` values(3223, 1);
	insert into `bill_author` values(3223, 3);
	insert into `bill_author` values(3223, 4);
	insert into `bill_author` values(3223, 5);
	insert into `bill_author` values(3223, 6);
	insert into `bill_author` values(3223, 9);
	insert into `bill_author` values(3223, 11);
	insert into `bill_author` values(3223, 12);
	insert into `bill_author` values(3223, 13);
	insert into `bill_author` values(3223, 14);
	insert into `bill_author` values(3223, 15);
	insert into `bill_author` values(3223, 16);



-- insert into `bill`
-- 	values(3224, 'title1', 'a super long body1', 'SENATE BILL', 'scope', 'pending', 'subj', '1st', curdate(), 1);


-- insert into `bill`
-- 	values(3225, 'title1', 'a super long body1', 'SENATE BILL', 'scope', 'pending', 'subj', '1st', curdate(), 1);


-- insert into `bill`
-- 	values(3226, 'title1', 'a super long body1', 'SENATE BILL', 'scope', 'pending', 'subj', '1st', curdate(), 1);


-- insert into `bill`
-- 	values(3227, 'title1', 'a super long body1', 'SENATE BILL', 'scope', 'pending', 'subj', '1st', curdate(), 1);


insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (1, 'Camel', 'Leddy', 'Broadbear', '05/20/1962', 'F', 'HOUSEMEMBER', 38631, 1, '6/9/2006', '5/11/2019');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (2, 'Brok', 'Minocchi', 'Claussen', '06/08/1943', 'M', 'SENATOR', 35919, 2, '10/15/2004', '11/7/2015');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (3, 'Huey', 'Werendell', 'Bridell', '01/23/1932', 'M', 'SENATOR', 24688, 1, '5/15/2014', '7/8/2013');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (4, 'Luca', 'Pantling', 'Robet', '11/12/1956', 'M', 'HOUSEMEMBER', 38749, 1, '6/1/2013', '3/13/2007');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (5, 'Gina', 'Sabbin', 'Conor', '02/20/1951', 'F', 'HOUSEMEMBER', 15302, 2, '1/29/2009', '5/18/2017');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (6, 'Gunar', 'Clendening', 'Danielis', '11/28/1937', 'M', 'SENATOR', 37688, 1, '11/3/2006', '12/9/2009');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (7, 'Candra', 'Mollnar', 'Raynton', '06/14/1964', 'F', 'SENATOR', 23408, 0, '5/26/2016', '7/27/2017');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (8, 'Cherri', 'Hempshall', 'Vowells', '08/11/1930', 'F', 'HOUSEMEMBER', 38902, 0, '11/28/2008', '1/1/2013');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (9, 'Kimbell', 'Crombleholme', 'Bratton', '11/09/1959', 'M', 'SENATOR', 14975, 1, '4/7/2011', '4/17/2006');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (10, 'Helsa', 'Frankcombe', 'Demead', '06/23/1939', 'F', 'SENATOR', 30057, 1, '12/24/2012', '1/24/2011');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (11, 'Cullan', 'Guidi', 'Gueste', '11/18/1958', 'M', 'SENATOR', 21748, 1, '7/30/2012', '8/11/2013');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (12, 'Sadie', 'Birtles', 'Macon', '07/04/1961', 'F', 'HOUSEMEMBER', 25742, 0, '2/11/2007', '8/11/2014');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (13, 'Ardine', 'Girardengo', 'Fraschini', '10/21/1947', 'F', 'HOUSEMEMBER', 30289, 0, '6/14/2006', '9/30/2017');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (14, 'Evania', 'Calafate', 'Tague', '11/29/1950', 'F', 'SENATOR', 20769, 2, '3/30/2011', '1/24/2016');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (15, 'Patin', 'Nisbet', 'Lenthall', '09/09/1937', 'M', 'HOUSEMEMBER', 20247, 1, '5/4/2016', '3/30/2009');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (16, 'Em', 'Geillier', 'Stile', '05/22/1970', 'F', 'HOUSEMEMBER', 29185, 1, '12/30/2007', '7/17/2004');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (17, 'Cory', 'Stockney', 'Charrisson', '10/13/1955', 'F', 'HOUSEMEMBER', 27416, 2, '4/1/2011', '8/22/2017');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (18, 'Mariska', 'Carbry', 'Tills', '06/21/1957', 'F', 'HOUSEMEMBER', 33364, 2, '6/7/2014', '12/29/2006');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (19, 'Lari', 'Gladden', 'Haworth', '09/23/1956', 'F', 'SENATOR', 25672, 2, '8/9/2007', '11/3/2011');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (20, 'Aldous', 'Greig', 'Forbes', '10/22/1954', 'M', 'SENATOR', 10739, 0, '1/22/2014', '1/28/2007');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (21, 'Natassia', 'Fetherston', 'Klaiser', '07/21/1969', 'F', 'SENATOR', 22617, 1, '12/2/2011', '3/8/2014');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (22, 'Mel', 'Moyles', 'Trussler', '08/26/1952', 'M', 'HOUSEMEMBER', 13043, 0, '10/3/2009', '12/23/2009');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (23, 'Liesa', 'Genney', 'Senechell', '08/29/1939', 'F', 'HOUSEMEMBER', 31114, 0, '12/12/2007', '3/26/2012');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (24, 'Auria', 'Tiery', 'McEnery', '09/05/1934', 'F', 'SENATOR', 37468, 2, '1/9/2011', '6/10/2005');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (25, 'Hilarius', 'McFeat', 'Kolodziejski', '04/14/1940', 'M', 'HOUSEMEMBER', 19175, 1, '5/17/2015', '4/2/2017');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (26, 'Ringo', 'Runnacles', 'Corzon', '12/18/1960', 'M', 'SENATOR', 18873, 0, '9/8/2009', '7/21/2015');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (27, 'Birch', 'Hevey', 'Finnes', '06/29/1943', 'M', 'SENATOR', 14759, 1, '5/28/2010', '3/6/2019');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (28, 'Fidelia', 'Waye', 'Scholey', '04/07/1937', 'F', 'SENATOR', 34703, 0, '6/8/2014', '2/19/2016');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (29, 'Osmund', 'Pardoe', 'Cossem', '04/06/1969', 'M', 'SENATOR', 26150, 1, '1/14/2010', '7/18/2008');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (30, 'Pearline', 'Buckwell', 'Gaven', '08/07/1946', 'F', 'SENATOR', 36310, 2, '5/17/2008', '6/18/2015');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (31, 'Laurie', 'Creigan', 'Deek', '03/31/1970', 'M', 'SENATOR', 35736, 0, '6/6/2016', '1/29/2004');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (32, 'Joann', 'Featherstonhalgh', 'Henrys', '01/15/1956', 'F', 'HOUSEMEMBER', 32623, 0, '5/12/2011', '2/18/2018');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (33, 'Ilene', 'Duthy', 'Ballston', '08/21/1961', 'F', 'SENATOR', 31429, 2, '10/29/2005', '2/21/2008');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (34, 'Emmery', 'Strutt', 'Guyon', '08/08/1959', 'M', 'SENATOR', 33879, 1, '10/3/2010', '5/8/2012');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (35, 'Portie', 'Farquar', 'Yitzhakov', '01/21/1932', 'M', 'SENATOR', 26512, 1, '3/19/2014', '9/2/2006');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (36, 'Ruperto', 'Fort', 'Coats', '09/13/1962', 'M', 'HOUSEMEMBER', 34347, 2, '1/3/2014', '7/11/2015');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (37, 'Odelinda', 'Standen', 'Sambidge', '08/15/1949', 'F', 'HOUSEMEMBER', 20009, 2, '2/6/2009', '9/26/2011');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (38, 'Alexis', 'Crayker', 'Coltart', '04/30/1966', 'F', 'HOUSEMEMBER', 29801, 1, '10/20/2014', '1/18/2008');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (39, 'Ardelle', 'Tows', 'Dimitrov', '07/07/1956', 'F', 'SENATOR', 23597, 1, '3/15/2012', '4/27/2006');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (40, 'Bradford', 'Chalcraft', 'Farndale', '03/30/1970', 'M', 'SENATOR', 11878, 0, '3/6/2006', '12/19/2016');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (41, 'Myrle', 'Joyner', 'Olyfant', '05/21/1933', 'F', 'SENATOR', 19837, 0, '7/23/2008', '11/19/2012');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (42, 'Karlotte', 'Lucock', 'Lusted', '01/21/1967', 'F', 'SENATOR', 35931, 0, '3/4/2010', '12/26/2012');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (43, 'Eddy', 'Fyndon', 'Astles', '09/15/1942', 'M', 'SENATOR', 36312, 1, '5/21/2015', '5/31/2018');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (44, 'Crissy', 'Lukianovich', 'Katte', '01/30/1934', 'F', 'HOUSEMEMBER', 18194, 0, '8/3/2009', '8/28/2006');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (45, 'Barbey', 'Sweeney', 'Canfer', '01/15/1970', 'F', 'HOUSEMEMBER', 36438, 0, '10/10/2007', '1/1/2010');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (46, 'Aundrea', 'Benton', 'Posvner', '11/25/1968', 'F', 'HOUSEMEMBER', 16417, 0, '6/4/2008', '1/13/2011');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (47, 'Rolf', 'Canning', 'Crowden', '03/13/1932', 'M', 'SENATOR', 24591, 1, '2/8/2005', '12/19/2007');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (48, 'Brockie', 'Gaw', 'Bagley', '10/28/1964', 'M', 'HOUSEMEMBER', 11781, 2, '12/27/2004', '7/16/2011');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (49, 'Fran', 'Broadberrie', 'Hamelyn', '03/09/1935', 'M', 'HOUSEMEMBER', 38082, 0, '10/29/2014', '9/26/2006');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (50, 'Olin', 'Robardey', 'Leser', '05/03/1931', 'M', 'HOUSEMEMBER', 15614, 2, '1/9/2009', '8/8/2008');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (51, 'Barbie', 'Fancott', 'Brosenius', '12/11/1937', 'F', 'HOUSEMEMBER', 14681, 2, '10/7/2005', '1/31/2014');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (52, 'Lenette', 'Burghill', 'Schruyer', '06/12/1967', 'F', 'SENATOR', 23547, 0, '2/24/2008', '1/17/2004');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (53, 'Zelda', 'Wyon', 'Melross', '04/08/1957', 'F', 'SENATOR', 29861, 1, '1/31/2006', '1/15/2011');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (54, 'Wilhelm', 'Lanston', 'Delph', '02/20/1943', 'M', 'SENATOR', 32669, 2, '5/3/2014', '3/28/2017');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (55, 'Emmalyn', 'Biddlestone', 'Seckington', '06/18/1965', 'F', 'HOUSEMEMBER', 23417, 2, '9/29/2007', '4/26/2007');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (56, 'Augustin', 'Jewers', 'Ellison', '03/04/1933', 'M', 'HOUSEMEMBER', 21305, 0, '5/31/2005', '1/13/2007');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (57, 'Martyn', 'Stickel', 'Napoli', '12/07/1952', 'M', 'HOUSEMEMBER', 10226, 0, '10/29/2013', '4/24/2004');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (58, 'Hyacinth', 'Radin', 'Sacks', '12/06/1964', 'F', 'HOUSEMEMBER', 27809, 0, '11/24/2011', '9/22/2016');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (59, 'Kerby', 'Stollmeier', 'Steart', '12/06/1964', 'M', 'SENATOR', 14350, 1, '4/3/2007', '6/11/2019');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (60, 'Allys', 'Sneaker', 'Wadworth', '11/16/1940', 'F', 'SENATOR', 30707, 0, '1/23/2014', '1/4/2016');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (61, 'Cordy', 'Farrance', 'Dumphries', '09/11/1936', 'F', 'HOUSEMEMBER', 35583, 1, '3/25/2004', '7/31/2008');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (62, 'Mortie', 'Grzegorzewicz', 'Rosbrough', '08/31/1960', 'M', 'SENATOR', 39532, 0, '5/21/2006', '8/2/2018');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (63, 'Benedikt', 'Grestie', 'Sandeford', '04/04/1967', 'M', 'HOUSEMEMBER', 16126, 0, '6/26/2008', '10/28/2015');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (64, 'Maison', 'Goodings', 'Motton', '03/18/1937', 'M', 'HOUSEMEMBER', 34476, 1, '6/2/2010', '8/26/2012');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (65, 'Kin', 'Gilderoy', 'Divall', '11/05/1960', 'M', 'SENATOR', 18091, 1, '7/26/2008', '10/12/2008');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (66, 'Burnaby', 'Hoffmann', 'Dodshun', '04/15/1967', 'M', 'SENATOR', 23746, 0, '6/12/2015', '1/25/2008');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (67, 'Stearne', 'Antonsen', 'Crystal', '04/30/1954', 'M', 'HOUSEMEMBER', 14026, 1, '1/8/2008', '7/18/2015');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (68, 'Hillyer', 'Stebbing', 'Winwright', '05/20/1943', 'M', 'HOUSEMEMBER', 22483, 0, '3/25/2006', '1/25/2017');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (69, 'Riccardo', 'Torrejon', 'Keeton', '05/09/1964', 'M', 'HOUSEMEMBER', 27647, 0, '9/26/2012', '8/16/2010');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (70, 'Donelle', 'Kerner', 'Leban', '11/29/1962', 'F', 'SENATOR', 27195, 2, '11/23/2014', '3/1/2017');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (71, 'Dennie', 'Dunthorne', 'Nicklen', '02/25/1938', 'M', 'HOUSEMEMBER', 36656, 2, '1/25/2013', '12/5/2018');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (72, 'Conny', 'Cleary', 'Flode', '07/18/1952', 'M', 'SENATOR', 12461, 2, '5/20/2007', '2/4/2004');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (73, 'Carolin', 'Johnston', 'Schoenleiter', '11/26/1962', 'F', 'HOUSEMEMBER', 25606, 1, '2/8/2013', '3/26/2007');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (74, 'Meridith', 'Kosel', 'Rilston', '03/11/1943', 'F', 'SENATOR', 10797, 2, '12/16/2008', '9/13/2019');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (75, 'Verena', 'Prater', 'Gronowe', '05/02/1938', 'F', 'SENATOR', 20213, 1, '3/23/2015', '7/29/2018');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (76, 'Sherlocke', 'Tetlow', 'Ficken', '10/09/1932', 'M', 'SENATOR', 38354, 1, '8/4/2004', '7/8/2015');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (77, 'Terrye', 'Bridie', 'Emblen', '12/04/1961', 'F', 'SENATOR', 20499, 0, '12/4/2012', '7/11/2005');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (78, 'Nikolai', 'Pach', 'Escala', '11/13/1961', 'M', 'HOUSEMEMBER', 16668, 2, '3/25/2014', '11/20/2007');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (79, 'Jolyn', 'Stebbin', 'Roos', '04/01/1946', 'F', 'HOUSEMEMBER', 17171, 1, '8/22/2007', '9/18/2011');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (80, 'Archer', 'Bruno', 'Kleinberer', '05/13/1956', 'M', 'HOUSEMEMBER', 17688, 0, '4/12/2005', '12/7/2013');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (81, 'Jourdain', 'Lehrer', 'O''Bradain', '12/29/1940', 'M', 'HOUSEMEMBER', 21149, 2, '5/29/2014', '12/27/2018');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (82, 'Kimberlyn', 'Hellwich', 'Minichi', '02/28/1943', 'F', 'SENATOR', 24180, 2, '5/27/2009', '5/1/2008');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (83, 'Prudi', 'Baish', 'Godfree', '08/27/1933', 'F', 'HOUSEMEMBER', 10592, 2, '4/29/2011', '4/25/2017');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (84, 'Cleon', 'Aristide', 'Itzchaki', '05/18/1965', 'M', 'HOUSEMEMBER', 10400, 1, '11/8/2013', '12/23/2011');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (85, 'Lulu', 'McNee', 'McQuorkell', '08/27/1940', 'F', 'SENATOR', 11445, 1, '7/5/2008', '1/17/2013');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (86, 'Nanine', 'Riquet', 'Manning', '08/14/1932', 'F', 'SENATOR', 36560, 0, '5/22/2009', '3/1/2018');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (87, 'Frederic', 'Cotmore', 'McVane', '07/04/1955', 'M', 'HOUSEMEMBER', 27375, 0, '12/12/2014', '4/5/2015');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (88, 'Bettye', 'McClintock', 'Ladewig', '06/13/1957', 'F', 'SENATOR', 15871, 0, '10/2/2012', '7/6/2007');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (89, 'Dell', 'Turle', 'Argo', '08/09/1967', 'M', 'HOUSEMEMBER', 25066, 1, '7/23/2016', '7/31/2006');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (90, 'Hewett', 'Oakenfall', 'Wiersma', '11/03/1969', 'M', 'SENATOR', 19150, 2, '9/9/2007', '6/15/2004');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (91, 'Sarena', 'Laughlan', 'Rentcome', '02/08/1937', 'F', 'HOUSEMEMBER', 23925, 0, '5/12/2009', '1/5/2014');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (92, 'Merwin', 'Eads', 'Brameld', '05/20/1967', 'M', 'HOUSEMEMBER', 15199, 0, '10/29/2006', '8/21/2018');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (93, 'Johannes', 'Whyler', 'Tootal', '12/15/1960', 'M', 'HOUSEMEMBER', 39559, 2, '6/8/2012', '6/3/2005');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (94, 'Evin', 'Macro', 'Chastney', '04/03/1955', 'M', 'HOUSEMEMBER', 39538, 0, '3/14/2013', '9/23/2008');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (95, 'Chilton', 'Radbond', 'Draisey', '02/27/1951', 'M', 'SENATOR', 14543, 0, '11/5/2011', '11/6/2007');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (96, 'Durward', 'Gloyens', 'Bidewell', '10/07/1965', 'M', 'SENATOR', 33409, 2, '3/19/2005', '10/24/2016');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (97, 'Paulette', 'Varsey', 'Jollands', '05/19/1937', 'F', 'HOUSEMEMBER', 27773, 1, '4/12/2012', '4/16/2008');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (98, 'Maren', 'Jobbins', 'Dodgshon', '05/18/1948', 'F', 'SENATOR', 35510, 1, '12/14/2012', '12/1/2016');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (99, 'Lona', 'Belch', 'Bell', '11/14/1967', 'F', 'HOUSEMEMBER', 36251, 2, '1/28/2007', '4/25/2012');
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (100, 'Fowler', 'Stainer', 'Poor', '06/20/1930', 'M', 'HOUSEMEMBER', 36570, 0, '6/24/2005', '4/15/2014');

insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (1, 'sem mauris', 'vestibulum ante ipsum', 'HouseBill', 'Provincial', 'Passed', '2nd', '6/23/2016');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (2, 'eros vestibulum ac est lacinia nisi', 'commodo vulputate justo in', 'SenateBill', 'Provincial', 'Pending', '3rd', '4/29/2009');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (3, 'sapien iaculis congue vivamus metus arcu adipiscing', 'mauris sit amet eros suspendisse accumsan tortor', 'HouseBill', 'Provincial', 'Passed', '3rd', '11/19/2009');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (4, 'varius', 'mattis pulvinar nulla pede ullamcorper augue', 'HouseBill', 'National', 'Passed', '3rd', '6/16/2013');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (5, 'in hac habitasse platea', 'arcu sed augue aliquam erat volutpat', 'SenateBill', 'Municipal', 'Pending', '2nd', '12/2/2014');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (6, 'volutpat sapien arcu sed augue aliquam erat volutpat', 'mauris vulputate elementum nullam varius nulla facilisi', 'SenateBill', 'Municipal', 'Passed','1st', '8/24/2012');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (7, 'et magnis dis parturient', 'ac neque duis bibendum morbi non quam', 'HouseBill', 'National', 'Pending', '2nd', '8/8/2009');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (8, 'turpis', 'nunc commodo placerat praesent blandit nam nulla', 'HouseBill', 'Provincial', 'Passed', '1st', '5/21/2011');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (9, 'habitasse', 'et ultrices posuere cubilia curae donec pharetra', 'SenateBill', 'National', 'Passed', '2nd', '5/28/2008');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (10, 'dui luctus rutrum', 'libero convallis eget eleifend', 'SenateBill', 'Municipal', 'Passed', '3rd', '9/14/2016');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (11, 'dui proin leo odio', 'ut odio cras', 'SenateBill', 'National', 'Pending', '1st', '7/5/2014');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (12, 'feugiat non pretium quis lectus', 'suscipit a feugiat et eros vestibulum ac', 'HouseBill', 'Provincial', 'Pending', '1st', '6/22/2004');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (13, 'consectetuer adipiscing elit proin', 'congue risus semper porta volutpat quam', 'SenateBill', 'Provincial', 'Pending', '2nd', '7/22/2009');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (14, 'et magnis', 'aliquam erat volutpat in congue etiam justo', 'SenateBill', 'National', 'Pending', '1st', '12/4/2007');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (15, 'enim', 'suspendisse ornare consequat lectus', 'SenateBill', 'National', 'Pending', '3rd', '7/15/2005');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (16, 'ac nibh fusce lacus purus aliquet at', 'eleifend donec ut', 'SenateBill', 'Provincial', 'Passed', '3rd', '11/30/2014');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (17, 'quis lectus suspendisse potenti in eleifend quam a', 'eu tincidunt in leo', 'SenateBill', 'Municipal', 'Passed', '1st', '8/31/2015');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (18, 'a ipsum integer', 'volutpat erat', 'SenateBill', 'Provincial', 'Passed', '2nd', '7/24/2006');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (19, 'eget semper rutrum nulla nunc purus phasellus in', 'vestibulum quam', 'SenateBill', 'Provincial', 'Passed', '2nd', '2/5/2004');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (20, 'faucibus accumsan odio curabitur convallis duis', 'at nulla suspendisse potenti cras in purus', 'HouseBill', 'Provincial', 'Passed', '1st', '2/22/2016');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (21, 'vel augue vestibulum rutrum', 'velit eu est congue elementum in', 'SenateBill', 'Provincial', 'Pending', '3rd', '9/18/2008');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (22, 'praesent', 'at vulputate vitae nisl aenean lectus pellentesque eget', 'HouseBill', 'Municipal', 'Passed', '2nd', '3/10/2013');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (23, 'nulla pede ullamcorper augue a suscipit nulla elit', 'aenean auctor gravida sem praesent', 'HouseBill', 'National', 'Pending', '2nd', '2/7/2007');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (24, 'vestibulum vestibulum ante ipsum primis', 'aliquam augue quam', 'HouseBill', 'National', 'Passed', '1st', '12/15/2004');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (25, 'sit amet eleifend pede libero quis orci nullam', 'platea dictumst aliquam augue quam sollicitudin vitae consectetuer', 'HouseBill', 'Provincial', 'Passed', '3rd', '3/17/2012');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (26, 'nascetur ridiculus', 'donec semper sapien a', 'SenateBill', 'Provincial', 'Passed', '3rd', '6/7/2014');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (27, 'aenean', 'ut volutpat sapien arcu', 'SenateBill', 'Provincial', 'Pending', '1st', '9/1/2014');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (28, 'molestie', 'nulla ac enim in tempor turpis', 'HouseBill', 'Municipal', 'Passed', '1st', '7/4/2015');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (29, 'sollicitudin vitae consectetuer eget rutrum at', 'duis at', 'HouseBill', 'National', 'Pending', '2nd', '4/8/2016');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (30, 'quam', 'erat eros viverra eget congue eget semper', 'SenateBill', 'Provincial', 'Passed', '2nd', '1/12/2011');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (31, 'mollis molestie lorem quisque', 'faucibus orci', 'SenateBill', 'National', 'Passed', '2nd', '5/6/2017');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (32, 'varius ut', 'convallis nulla neque libero convallis eget eleifend', 'HouseBill', 'Provincial', 'Pending', '1st', '11/2/2017');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (33, 'orci luctus et ultrices posuere cubilia', 'nec dui luctus rutrum nulla', 'SenateBill', 'National', 'Pending', '2nd', '11/24/2011');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (34, 'tempus vivamus in felis', 'nulla', 'SenateBill', 'Municipal', 'Passed', '1st', '4/28/2015');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (35, 'vitae nisi nam ultrices libero non', 'lectus suspendisse', 'HouseBill', 'Municipal', 'Passed', '3rd', '12/5/2012');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (36, 'imperdiet sapien urna pretium nisl ut volutpat', 'neque sapien placerat ante nulla justo aliquam quis', 'HouseBill', 'Provincial', 'Passed', '2nd', '8/25/2011');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (37, 'pulvinar lobortis est', 'nisi at nibh', 'SenateBill', 'Provincial', 'Pending', '2nd', '8/9/2017');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (38, 'auctor', 'sapien dignissim vestibulum vestibulum ante', 'SenateBill', 'Provincial', 'Passed', '1st', '3/10/2004');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (39, 'luctus', 'elit proin risus praesent lectus vestibulum quam', 'HouseBill', 'Municipal', 'Pending', '1st', '8/21/2007');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (40, 'gravida sem praesent id massa id nisl venenatis', 'fringilla rhoncus mauris enim leo rhoncus sed vestibulum', 'SenateBill', 'Provincial', 'Passed', '1st', '1/18/2009');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (41, 'sit amet sapien', 'primis in faucibus orci', 'SenateBill', 'Municipal', 'Passed', '2nd', '7/19/2009');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (42, 'nibh fusce', 'eget orci vehicula', 'SenateBill', 'Municipal', 'Passed', '1st', '3/1/2010');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (43, 'nulla tempus vivamus in felis eu sapien cursus', 'diam cras pellentesque volutpat', 'HouseBill', 'Provincial', 'Pending', '2nd', '2/21/2004');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (44, 'vestibulum ac est', 'rutrum at lorem integer', 'HouseBill', 'Provincial', 'Passed', '1st', '6/21/2015');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (45, 'accumsan tortor quis turpis', 'nullam orci pede venenatis non sodales sed', 'SenateBill', 'National', 'Passed', '1st', '1/15/2016');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (46, 'suscipit a feugiat et eros vestibulum', 'penatibus et magnis dis parturient', 'SenateBill', 'National', 'Passed', '3rd', '5/4/2012');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (47, 'felis eu sapien cursus vestibulum proin', 'mi pede malesuada in imperdiet et commodo', 'SenateBill', 'Provincial', 'Pending', '3rd', '4/16/2015');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (48, 'sed augue aliquam erat volutpat in congue', 'nec molestie', 'SenateBill', 'Provincial', 'Passed', '2nd', '6/18/2013');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (49, 'eros', 'eget tincidunt', 'HouseBill', 'Provincial', 'Pending', '1st', '5/12/2006');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (50, 'justo lacinia', 'proin leo', 'SenateBill', 'Provincial', 'Passed', '3rd', '6/12/2014');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (51, 'justo aliquam quis turpis', 'ridiculus mus vivamus vestibulum sagittis sapien cum sociis', 'HouseBill', 'Provincial', 'Pending', '1st', '9/8/2005');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (52, 'nulla facilisi cras non velit nec', 'convallis morbi odio odio elementum eu', 'HouseBill', 'Municipal', 'Passed', '2nd', '3/31/2004');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (53, 'accumsan felis ut at', 'vestibulum ante ipsum primis in faucibus orci', 'HouseBill', 'National', 'Passed', '2nd', '6/22/2007');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (54, 'urna pretium nisl ut volutpat sapien arcu sed', 'mauris enim leo', 'SenateBill', 'Provincial', 'Pending', '2nd', '9/15/2011');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (55, 'volutpat in congue etiam justo etiam', 'sed ante vivamus tortor duis', 'SenateBill', 'Provincial', 'Passed', '2nd', '9/21/2012');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (56, 'mauris enim leo rhoncus', 'sed vel enim sit amet nunc viverra dapibus', 'HouseBill', 'Municipal', 'Pending', '3rd', '6/7/2011');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (57, 'magna vulputate', 'sollicitudin vitae consectetuer eget', 'SenateBill', 'National', 'Passed', '1st', '11/21/2015');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (58, 'id lobortis convallis tortor risus dapibus augue', 'amet cursus', 'HouseBill', 'Provincial', 'Pending', '2nd', '4/13/2016');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (59, 'pellentesque ultrices phasellus id sapien in', 'vestibulum ante ipsum primis in faucibus orci luctus', 'SenateBill', 'Municipal', 'Passed', '1st', '8/12/2015');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (60, 'gravida sem praesent id', 'nunc vestibulum ante ipsum primis', 'SenateBill', 'Provincial', 'Pending', '3rd', '1/29/2010');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (61, 'ut at dolor quis', 'eleifend pede libero quis orci nullam', 'HouseBill', 'Provincial', 'Passed', '1st', '4/15/2006');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (62, 'metus aenean fermentum donec ut mauris', 'ipsum primis in', 'HouseBill', 'Provincial', 'Passed', '2nd', '3/17/2008');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (63, 'magnis dis parturient montes nascetur ridiculus', 'elementum', 'HouseBill', 'Provincial', 'Passed', '1st', '5/13/2013');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (64, 'nulla ut erat id mauris vulputate', 'quisque arcu libero rutrum', 'HouseBill', 'Provincial', 'Passed', '3rd', '7/30/2009');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (65, 'lacus morbi quis tortor id nulla', 'id justo sit', 'SenateBill', 'Provincial', 'Passed', '2nd', '3/4/2015');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (66, 'in est', 'in faucibus orci luctus et ultrices posuere cubilia', 'HouseBill', 'Provincial', 'Pending', '1st', '9/10/2010');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (67, 'et magnis dis parturient montes nascetur ridiculus', 'sed interdum venenatis turpis enim blandit', 'HouseBill', 'Municipal', 'Passed', '1st', '3/15/2012');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (68, 'nam congue risus semper', 'leo', 'HouseBill', 'Provincial', 'Pending', '2nd', '6/19/2016');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (69, 'molestie nibh in lectus', 'elementum pellentesque quisque porta', 'HouseBill', 'Provincial', 'Pending', '2nd', '9/28/2011');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (70, 'dolor', 'phasellus id sapien in sapien iaculis', 'HouseBill', 'Provincial', 'Pending', '3rd', '3/6/2008');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (71, 'nisl duis', 'dapibus duis at velit', 'HouseBill', 'National', 'Pending', '3rd', '1/29/2005');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (72, 'quisque id justo', 'in lectus pellentesque at nulla suspendisse potenti cras', 'SenateBill', 'Provincial', 'Pending', '3rd', '9/9/2014');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (73, 'lacus morbi quis', 'curae', 'SenateBill', 'National', 'Passed', '1st', '8/13/2005');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (74, 'adipiscing molestie hendrerit', 'rhoncus dui vel sem sed sagittis nam congue', 'HouseBill', 'Provincial', 'Passed', '2nd', '10/11/2006');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (75, 'neque duis bibendum morbi non quam nec', 'ullamcorper augue a', 'HouseBill', 'Provincial', 'Pending', '3rd', '11/10/2005');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (76, 'blandit non interdum in ante vestibulum ante', 'id lobortis convallis tortor risus dapibus augue vel', 'HouseBill', 'Provincial', 'Passed', '3rd', '8/6/2013');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (77, 'sem praesent id massa id nisl', 'ut at dolor', 'SenateBill', 'Municipal', 'Passed', '3rd', '10/7/2014');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (78, 'non pretium quis', 'id nulla ultrices aliquet maecenas leo', 'HouseBill', 'Municipal', 'Pending', '3rd', '10/3/2014');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (79, 'eget orci vehicula condimentum', 'nulla quisque arcu libero rutrum ac', 'HouseBill', 'Municipal', 'Passed', '3rd', '2/17/2007');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (80, 'ac lobortis', 'rutrum ac lobortis', 'SenateBill', 'Provincial', 'Passed', '2nd', '3/13/2007');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (81, 'at diam nam tristique tortor eu pede', 'blandit nam nulla integer', 'HouseBill', 'Provincial', 'Pending', '3rd', '6/5/2008');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (82, 'quis lectus suspendisse potenti', 'consequat', 'HouseBill', 'Provincial', 'Passed', '1st', '9/19/2012');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (83, 'in est', 'orci luctus et ultrices', 'HouseBill', 'Provincial', 'Pending', '2nd', '12/29/2007');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (84, 'condimentum neque', 'sollicitudin vitae consectetuer eget rutrum', 'SenateBill', 'Provincial', 'Passed', '1st', '10/7/2005');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (85, 'vivamus vestibulum sagittis', 'nec dui', 'HouseBill', 'National', 'Passed', '3rd', '6/19/2012');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (86, 'nascetur ridiculus mus etiam vel', 'est quam pharetra magna ac consequat metus sapien', 'SenateBill', 'Municipal', 'Passed', '2nd', '12/7/2007');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (87, 'dis parturient montes nascetur ridiculus', 'vestibulum sit amet', 'SenateBill', 'Provincial', 'Pending', '3rd', '5/14/2016');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (88, 'morbi', 'nulla sed accumsan felis', 'HouseBill', 'Provincial', 'Pending', '2nd', '9/17/2014');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (89, 'nec euismod scelerisque quam turpis adipiscing', 'consequat varius', 'SenateBill', 'Provincial', 'Passed', '1st', '3/19/2009');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (90, 'ac consequat', 'mauris eget massa tempor convallis', 'SenateBill', 'National', 'Passed', '1st', '4/4/2007');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (91, 'amet consectetuer adipiscing elit proin interdum', 'duis', 'HouseBill', 'National', 'Pending', '2nd', '4/13/2008');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (92, 'nec nisi volutpat eleifend donec ut dolor', 'ipsum ac tellus semper interdum mauris', 'HouseBill', 'Municipal', 'Pending', '3rd', '11/18/2007');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (93, 'vulputate', 'turpis', 'HouseBill', 'Municipal', 'Pending', '3rd', '11/17/2005');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (94, 'erat quisque', 'metus aenean fermentum donec ut mauris', 'HouseBill', 'National', 'Passed', '1st', '2/8/2008');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (95, 'morbi quis tortor id', 'mattis pulvinar nulla pede ullamcorper augue a', 'SenateBill', 'Municipal', 'Passed', '1st', '4/1/2005');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (96, 'augue', 'elit proin risus praesent lectus vestibulum', 'SenateBill', 'National', 'Pending', '2nd', '12/8/2006');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (97, 'rhoncus', 'imperdiet sapien urna pretium nisl ut volutpat', 'SenateBill', 'Provincial', 'Passed', '1st', '6/24/2009');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (98, 'iaculis diam', 'nullam molestie nibh in lectus pellentesque at nulla', 'SenateBill', 'National', 'Passed', '3rd', '7/4/2007');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (99, 'sed interdum venenatis', 'maecenas pulvinar lobortis est phasellus sit', 'SenateBill', 'Municipal', 'Passed', '1st', '9/21/2012');
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (100, 'phasellus id sapien in sapien iaculis congue', 'libero quis orci nullam molestie nibh in lectus', 'SenateBill', 'National', 'Passed', '3rd', '5/24/2004');

insert into bill_author (billno, empid) values (84, 28);
insert into bill_author (billno, empid) values (31, 22);
insert into bill_author (billno, empid) values (65, 98);
insert into bill_author (billno, empid) values (21, 66);
insert into bill_author (billno, empid) values (23, 38);
insert into bill_author (billno, empid) values (44, 93);
insert into bill_author (billno, empid) values (2, 6);
insert into bill_author (billno, empid) values (50, 51);
insert into bill_author (billno, empid) values (5, 92);
insert into bill_author (billno, empid) values (68, 29);
insert into bill_author (billno, empid) values (29, 57);
insert into bill_author (billno, empid) values (75, 29);
insert into bill_author (billno, empid) values (79, 9);
insert into bill_author (billno, empid) values (68, 69);
insert into bill_author (billno, empid) values (55, 91);
insert into bill_author (billno, empid) values (14, 12);
insert into bill_author (billno, empid) values (73, 77);
insert into bill_author (billno, empid) values (80, 5);
insert into bill_author (billno, empid) values (67, 31);
insert into bill_author (billno, empid) values (4, 44);
insert into bill_author (billno, empid) values (77, 37);
insert into bill_author (billno, empid) values (78, 60);
insert into bill_author (billno, empid) values (71, 89);
insert into bill_author (billno, empid) values (87, 28);
insert into bill_author (billno, empid) values (1, 81);
insert into bill_author (billno, empid) values (21, 100);
insert into bill_author (billno, empid) values (11, 78);
insert into bill_author (billno, empid) values (46, 11);
insert into bill_author (billno, empid) values (28, 2);
insert into bill_author (billno, empid) values (58, 47);
insert into bill_author (billno, empid) values (20, 40);
insert into bill_author (billno, empid) values (93, 89);
insert into bill_author (billno, empid) values (48, 86);
insert into bill_author (billno, empid) values (95, 55);
insert into bill_author (billno, empid) values (28, 48);
insert into bill_author (billno, empid) values (76, 27);
insert into bill_author (billno, empid) values (10, 23);
insert into bill_author (billno, empid) values (82, 10);
insert into bill_author (billno, empid) values (61, 11);
insert into bill_author (billno, empid) values (75, 54);
insert into bill_author (billno, empid) values (12, 28);
insert into bill_author (billno, empid) values (43, 12);
insert into bill_author (billno, empid) values (57, 18);
insert into bill_author (billno, empid) values (77, 30);
insert into bill_author (billno, empid) values (56, 40);
insert into bill_author (billno, empid) values (60, 29);
insert into bill_author (billno, empid) values (52, 68);
insert into bill_author (billno, empid) values (42, 67);
insert into bill_author (billno, empid) values (78, 99);
insert into bill_author (billno, empid) values (24, 46);
insert into bill_author (billno, empid) values (12, 69);
insert into bill_author (billno, empid) values (50, 45);
insert into bill_author (billno, empid) values (18, 54);
insert into bill_author (billno, empid) values (37, 88);
insert into bill_author (billno, empid) values (20, 27);
insert into bill_author (billno, empid) values (97, 90);
insert into bill_author (billno, empid) values (87, 100);
insert into bill_author (billno, empid) values (3, 81);
insert into bill_author (billno, empid) values (66, 92);
insert into bill_author (billno, empid) values (27, 65);
insert into bill_author (billno, empid) values (39, 35);
insert into bill_author (billno, empid) values (65, 98);
insert into bill_author (billno, empid) values (34, 6);
insert into bill_author (billno, empid) values (42, 99);
insert into bill_author (billno, empid) values (60, 45);
insert into bill_author (billno, empid) values (92, 19);
insert into bill_author (billno, empid) values (47, 41);
insert into bill_author (billno, empid) values (85, 16);
insert into bill_author (billno, empid) values (72, 29);
insert into bill_author (billno, empid) values (18, 90);
insert into bill_author (billno, empid) values (16, 44);
insert into bill_author (billno, empid) values (14, 84);
insert into bill_author (billno, empid) values (17, 77);
insert into bill_author (billno, empid) values (79, 41);
insert into bill_author (billno, empid) values (20, 84);
insert into bill_author (billno, empid) values (59, 30);
insert into bill_author (billno, empid) values (39, 95);
insert into bill_author (billno, empid) values (59, 99);
insert into bill_author (billno, empid) values (1, 72);
insert into bill_author (billno, empid) values (87, 96);
insert into bill_author (billno, empid) values (86, 75);
insert into bill_author (billno, empid) values (32, 100);
insert into bill_author (billno, empid) values (74, 63);
insert into bill_author (billno, empid) values (73, 6);
insert into bill_author (billno, empid) values (63, 30);
insert into bill_author (billno, empid) values (36, 55);
insert into bill_author (billno, empid) values (50, 96);
insert into bill_author (billno, empid) values (3, 10);
insert into bill_author (billno, empid) values (37, 54);
insert into bill_author (billno, empid) values (97, 81);
insert into bill_author (billno, empid) values (31, 36);
insert into bill_author (billno, empid) values (84, 26);
insert into bill_author (billno, empid) values (68, 62);
insert into bill_author (billno, empid) values (68, 86);
insert into bill_author (billno, empid) values (65, 25);
insert into bill_author (billno, empid) values (20, 32);
insert into bill_author (billno, empid) values (23, 32);
insert into bill_author (billno, empid) values (47, 10);
insert into bill_author (billno, empid) values (74, 59);
insert into bill_author (billno, empid) values (14, 31);
insert into bill_author (billno, empid) values (36, 4);
insert into bill_author (billno, empid) values (97, 72);
insert into bill_author (billno, empid) values (6, 44);
insert into bill_author (billno, empid) values (2, 26);
insert into bill_author (billno, empid) values (32, 96);
insert into bill_author (billno, empid) values (38, 84);
insert into bill_author (billno, empid) values (12, 86);
insert into bill_author (billno, empid) values (74, 35);
insert into bill_author (billno, empid) values (94, 78);
insert into bill_author (billno, empid) values (86, 25);
insert into bill_author (billno, empid) values (54, 86);
insert into bill_author (billno, empid) values (31, 5);
insert into bill_author (billno, empid) values (55, 91);
insert into bill_author (billno, empid) values (26, 12);
insert into bill_author (billno, empid) values (88, 25);
insert into bill_author (billno, empid) values (14, 77);
insert into bill_author (billno, empid) values (63, 95);
insert into bill_author (billno, empid) values (73, 67);
insert into bill_author (billno, empid) values (99, 29);
insert into bill_author (billno, empid) values (46, 15);
insert into bill_author (billno, empid) values (74, 86);
insert into bill_author (billno, empid) values (36, 82);
insert into bill_author (billno, empid) values (25, 76);
insert into bill_author (billno, empid) values (88, 10);
insert into bill_author (billno, empid) values (1, 29);
insert into bill_author (billno, empid) values (4, 59);
insert into bill_author (billno, empid) values (31, 23);
insert into bill_author (billno, empid) values (81, 68);
insert into bill_author (billno, empid) values (61, 64);
insert into bill_author (billno, empid) values (9, 29);
insert into bill_author (billno, empid) values (7, 19);
insert into bill_author (billno, empid) values (97, 47);
insert into bill_author (billno, empid) values (97, 44);
insert into bill_author (billno, empid) values (6, 90);
insert into bill_author (billno, empid) values (22, 18);
insert into bill_author (billno, empid) values (64, 90);
insert into bill_author (billno, empid) values (52, 77);
insert into bill_author (billno, empid) values (77, 59);
insert into bill_author (billno, empid) values (70, 29);
insert into bill_author (billno, empid) values (6, 74);
insert into bill_author (billno, empid) values (55, 26);
insert into bill_author (billno, empid) values (93, 66);
insert into bill_author (billno, empid) values (97, 57);
insert into bill_author (billno, empid) values (17, 43);
insert into bill_author (billno, empid) values (64, 24);
insert into bill_author (billno, empid) values (60, 19);
insert into bill_author (billno, empid) values (34, 29);
insert into bill_author (billno, empid) values (42, 5);
insert into bill_author (billno, empid) values (33, 35);
insert into bill_author (billno, empid) values (5, 54);

insert into bill_subject (billno, subject) values (55, 'ullamcorper');
insert into bill_subject (billno, subject) values (80, 'ut massa volutpat convallis morbi odio');
insert into bill_subject (billno, subject) values (88, 'et');
insert into bill_subject (billno, subject) values (74, 'phasellus id sapien in sapien iaculis congue vivamus');
insert into bill_subject (billno, subject) values (48, 'dolor sit amet consectetuer adipiscing elit proin risus');
insert into bill_subject (billno, subject) values (21, 'at lorem integer tincidunt ante vel ipsum praesent');
insert into bill_subject (billno, subject) values (2, 'metus arcu');
insert into bill_subject (billno, subject) values (12, 'nunc purus phasellus in');
insert into bill_subject (billno, subject) values (28, 'neque duis bibendum morbi non');
insert into bill_subject (billno, subject) values (67, 'in congue etiam');
insert into bill_subject (billno, subject) values (8, 'ultrices posuere cubilia curae mauris viverra diam');
insert into bill_subject (billno, subject) values (19, 'amet lobortis sapien sapien');
insert into bill_subject (billno, subject) values (100, 'interdum eu tincidunt in');
insert into bill_subject (billno, subject) values (49, 'natoque penatibus et magnis dis parturient montes');
insert into bill_subject (billno, subject) values (77, 'lobortis convallis tortor risus');
insert into bill_subject (billno, subject) values (13, 'duis ac nibh fusce lacus purus');
insert into bill_subject (billno, subject) values (31, 'sapien urna pretium nisl ut volutpat sapien');
insert into bill_subject (billno, subject) values (26, 'penatibus et magnis dis parturient montes');
insert into bill_subject (billno, subject) values (65, 'est et tempus');
insert into bill_subject (billno, subject) values (14, 'nascetur');
insert into bill_subject (billno, subject) values (24, 'a pede posuere nonummy integer non velit donec');
insert into bill_subject (billno, subject) values (60, 'dapibus dolor vel est donec');
insert into bill_subject (billno, subject) values (71, 'non sodales sed tincidunt eu felis fusce');
insert into bill_subject (billno, subject) values (74, 'vitae mattis nibh ligula nec');
insert into bill_subject (billno, subject) values (36, 'lobortis ligula sit amet eleifend pede libero');
insert into bill_subject (billno, subject) values (91, 'sapien arcu sed augue aliquam');
insert into bill_subject (billno, subject) values (54, 'non pretium quis');
insert into bill_subject (billno, subject) values (26, 'ultrices posuere cubilia curae');
insert into bill_subject (billno, subject) values (6, 'tristique est et tempus');
insert into bill_subject (billno, subject) values (77, 'viverra diam vitae quam suspendisse potenti nullam porttitor');
insert into bill_subject (billno, subject) values (50, 'justo');
insert into bill_subject (billno, subject) values (86, 'pede lobortis ligula');
insert into bill_subject (billno, subject) values (40, 'primis');
insert into bill_subject (billno, subject) values (71, 'elementum');
insert into bill_subject (billno, subject) values (12, 'donec');
insert into bill_subject (billno, subject) values (62, 'tellus in sagittis dui vel nisl duis');
insert into bill_subject (billno, subject) values (14, 'consequat in');
insert into bill_subject (billno, subject) values (77, 'dui nec');
insert into bill_subject (billno, subject) values (49, 'ante');
insert into bill_subject (billno, subject) values (17, 'aenean lectus pellentesque eget nunc donec quis orci');
insert into bill_subject (billno, subject) values (93, 'in quis justo maecenas rhoncus aliquam lacus morbi');
insert into bill_subject (billno, subject) values (39, 'lacinia eget tincidunt eget tempus');
insert into bill_subject (billno, subject) values (36, 'tristique fusce');
insert into bill_subject (billno, subject) values (14, 'nec sem duis');
insert into bill_subject (billno, subject) values (97, 'non lectus aliquam sit');
insert into bill_subject (billno, subject) values (50, 'lobortis ligula');
insert into bill_subject (billno, subject) values (40, 'curae nulla dapibus');
insert into bill_subject (billno, subject) values (100, 'vestibulum vestibulum ante ipsum primis in faucibus orci');
insert into bill_subject (billno, subject) values (11, 'cursus urna');
insert into bill_subject (billno, subject) values (36, 'platea dictumst etiam faucibus cursus');
insert into bill_subject (billno, subject) values (21, 'fusce congue diam id ornare');
insert into bill_subject (billno, subject) values (17, 'odio justo sollicitudin');
insert into bill_subject (billno, subject) values (47, 'est risus');
insert into bill_subject (billno, subject) values (30, 'tellus in sagittis');
insert into bill_subject (billno, subject) values (9, 'bibendum felis sed interdum venenatis turpis enim');
insert into bill_subject (billno, subject) values (25, 'dolor morbi vel lectus in');
insert into bill_subject (billno, subject) values (14, 'vestibulum ante ipsum primis in faucibus orci');
insert into bill_subject (billno, subject) values (79, 'faucibus orci luctus et ultrices posuere cubilia');
insert into bill_subject (billno, subject) values (36, 'phasellus id sapien in');
insert into bill_subject (billno, subject) values (26, 'amet');
insert into bill_subject (billno, subject) values (80, 'vestibulum vestibulum ante ipsum primis in');
insert into bill_subject (billno, subject) values (31, 'luctus tincidunt nulla mollis molestie lorem quisque');
insert into bill_subject (billno, subject) values (38, 'sed');
insert into bill_subject (billno, subject) values (40, 'venenatis lacinia aenean sit amet justo morbi ut');
insert into bill_subject (billno, subject) values (41, 'turpis a');
insert into bill_subject (billno, subject) values (94, 'diam erat fermentum justo nec condimentum neque sapien');
insert into bill_subject (billno, subject) values (97, 'in faucibus');
insert into bill_subject (billno, subject) values (67, 'sociis natoque');
insert into bill_subject (billno, subject) values (41, 'lorem vitae mattis nibh ligula nec sem duis');
insert into bill_subject (billno, subject) values (12, 'nulla dapibus dolor vel est');
insert into bill_subject (billno, subject) values (98, 'morbi odio odio elementum eu');
insert into bill_subject (billno, subject) values (49, 'arcu sed augue');
insert into bill_subject (billno, subject) values (12, 'vestibulum ante ipsum primis');
insert into bill_subject (billno, subject) values (57, 'vel accumsan tellus');
insert into bill_subject (billno, subject) values (29, 'massa tempor convallis');
insert into bill_subject (billno, subject) values (52, 'lacus morbi quis tortor id');
insert into bill_subject (billno, subject) values (49, 'praesent id massa id nisl venenatis lacinia');
insert into bill_subject (billno, subject) values (95, 'curae donec pharetra magna vestibulum');
insert into bill_subject (billno, subject) values (9, 'convallis duis consequat dui');
insert into bill_subject (billno, subject) values (5, 'integer pede justo lacinia eget');
insert into bill_subject (billno, subject) values (53, 'vivamus');
insert into bill_subject (billno, subject) values (10, 'pharetra magna vestibulum aliquet ultrices erat');
insert into bill_subject (billno, subject) values (9, 'vestibulum ante ipsum primis in faucibus orci');
insert into bill_subject (billno, subject) values (55, 'magna at nunc commodo placerat');
insert into bill_subject (billno, subject) values (17, 'justo');
insert into bill_subject (billno, subject) values (85, 'elit proin');
insert into bill_subject (billno, subject) values (23, 'consectetuer eget rutrum at lorem integer tincidunt ante');
insert into bill_subject (billno, subject) values (90, 'nec sem duis aliquam convallis nunc');
insert into bill_subject (billno, subject) values (15, 'adipiscing');
insert into bill_subject (billno, subject) values (57, 'quam a odio in');
insert into bill_subject (billno, subject) values (92, 'aenean auctor gravida sem praesent id massa');
insert into bill_subject (billno, subject) values (46, 'aliquam convallis nunc proin at turpis a');
insert into bill_subject (billno, subject) values (86, 'ac');
insert into bill_subject (billno, subject) values (55, 'sem sed sagittis');
insert into bill_subject (billno, subject) values (53, 'vivamus vel nulla');
insert into bill_subject (billno, subject) values (15, 'a pede posuere nonummy integer');
insert into bill_subject (billno, subject) values (75, 'pharetra magna ac consequat');
insert into bill_subject (billno, subject) values (74, 'molestie');
insert into bill_subject (billno, subject) values (8, 'at nulla suspendisse potenti cras in purus eu');
insert into bill_subject (billno, subject) values (68, 'odio odio elementum eu interdum eu');
